# escape=`
FROM yadamu/svr:vs22
#
ADD https://cdn.mysql.com//Downloads/MySQL-8.1/mysql-8.1.0-winx64.zip .
ADD https://cdn.mysql.com//Downloads/MySQL-Shell/mysql-shell-8.1.1-windows-x86-64bit.zip .
RUN Expand-Archive -Path C:\mysql-8.1.0-winx64.zip -destinationPath """C:\Program Files\MySQL"""; ` 
    Expand-Archive -Path C:\mysql-shell-8.1.1-windows-x86-64bit.zip  -destinationPath """C:\Program Files\MySQL"""; ` 
    Remove-Item mysql-8.1.0-winx64.zip; `
    Remove-Item mysql-shell-8.1.1-windows-x86-64bit.zip ; `
    Move-Item """C:\Program Files\MySQL\mysql-8.1.1-winx64""" """C:\Program Files\MySQL\8.1"""; `
    Move-Item """C:\Program Files\MySQL\mysql-shell-8.1.1-windows-x86-64bit""" """C:\Program Files\MySQL\8.1\Shell"""; `
    [Environment]::SetEnvironmentVariable("""Path""", """C:\Program Files\MySQL\8.1\bin;C:\Program Files\MySQL\8.1\Shell\bin;""" +  $env:Path,"""Machine"""); 
#
COPY my.ini c:/windows
#
# Defer creation of instance to Start.ps1. This allows volumes and hostnames to be assigned using "Docker RUN" or "Docker-Compose"
#
COPY Start.ps1 .
ENTRYPOINT ["powershell","c:\\Start.ps1"]
#ENTRYPOINT ["powershell","wait-event"]
