--
:setvar DATABASE Northwind
use $(database)$(id1)
:setvar SCHEMA dbo
DECLARE @SOURCE_DATABASE NVARCHAR(128) = '$(DATABASE)$(ID1)'
DECLARE @TARGET_DATABASE NVARCHAR(128) = '$(DATABASE)$(ID2)'
DECLARE @SOURCE_SCHEMA NVARCHAR(128) = '$(SCHEMA)'
DECLARE @TARGET_SCHEMA NVARCHAR(128) = '$(SCHEMA)'
--
exec sp_COMPARE_SCHEMA TRUE, @SOURCE_DATABASE, @SOURCE_SCHEMA, @TARGET_DATABASE, @TARGET_SCHEMA, '$(METHOD)'
go
--
:setvar DATABASE AdventureWorks
use $(database)$(id1)
:setvar SCHEMA Sales
DECLARE @SOURCE_DATABASE NVARCHAR(128) = '$(DATABASE)$(ID1)'
DECLARE @TARGET_DATABASE NVARCHAR(128) = '$(DATABASE)$(ID2)'
DECLARE @SOURCE_SCHEMA NVARCHAR(128) = '$(SCHEMA)'
DECLARE @TARGET_SCHEMA NVARCHAR(128) = '$(SCHEMA)'
--
exec sp_COMPARE_SCHEMA TRUE, @SOURCE_DATABASE, @SOURCE_SCHEMA, @TARGET_DATABASE, @TARGET_SCHEMA, '$(METHOD)'
go
--
:setvar SCHEMA Person
DECLARE @SOURCE_DATABASE NVARCHAR(128) = '$(DATABASE)$(ID1)'
DECLARE @TARGET_DATABASE NVARCHAR(128) = '$(DATABASE)$(ID2)'
DECLARE @SOURCE_SCHEMA NVARCHAR(128) = '$(SCHEMA)'
DECLARE @TARGET_SCHEMA NVARCHAR(128) = '$(SCHEMA)'
--
exec sp_COMPARE_SCHEMA TRUE, @SOURCE_DATABASE, @SOURCE_SCHEMA, @TARGET_DATABASE, @TARGET_SCHEMA, '$(METHOD)'
go
--
:setvar SCHEMA Production
DECLARE @SOURCE_DATABASE NVARCHAR(128) = '$(DATABASE)$(ID1)'
DECLARE @TARGET_DATABASE NVARCHAR(128) = '$(DATABASE)$(ID2)'
DECLARE @SOURCE_SCHEMA NVARCHAR(128) = '$(SCHEMA)'
DECLARE @TARGET_SCHEMA NVARCHAR(128) = '$(SCHEMA)'
--
exec sp_COMPARE_SCHEMA TRUE, @SOURCE_DATABASE, @SOURCE_SCHEMA, @TARGET_DATABASE, @TARGET_SCHEMA, '$(METHOD)'
go
--
:setvar SCHEMA Purchasing
DECLARE @SOURCE_DATABASE NVARCHAR(128) = '$(DATABASE)$(ID1)'
DECLARE @TARGET_DATABASE NVARCHAR(128) = '$(DATABASE)$(ID2)'
DECLARE @SOURCE_SCHEMA NVARCHAR(128) = '$(SCHEMA)'
DECLARE @TARGET_SCHEMA NVARCHAR(128) = '$(SCHEMA)'
--
exec sp_COMPARE_SCHEMA TRUE, @SOURCE_DATABASE, @SOURCE_SCHEMA, @TARGET_DATABASE, @TARGET_SCHEMA, '$(METHOD)'
go
--
:setvar SCHEMA HumanResources
DECLARE @SOURCE_DATABASE NVARCHAR(128) = '$(DATABASE)$(ID1)'
DECLARE @TARGET_DATABASE NVARCHAR(128) = '$(DATABASE)$(ID2)'
DECLARE @SOURCE_SCHEMA NVARCHAR(128) = '$(SCHEMA)'
DECLARE @TARGET_SCHEMA NVARCHAR(128) = '$(SCHEMA)'
--
exec sp_COMPARE_SCHEMA TRUE, @SOURCE_DATABASE, @SOURCE_SCHEMA, @TARGET_DATABASE, @TARGET_SCHEMA, '$(METHOD)'
go
--
:setvar DATABASE AdventureWorksDW
use $(database)$(id1)
:setvar SCHEMA dbo
DECLARE @SOURCE_DATABASE NVARCHAR(128) = '$(DATABASE)$(ID1)'
DECLARE @TARGET_DATABASE NVARCHAR(128) = '$(DATABASE)$(ID2)'
DECLARE @SOURCE_SCHEMA NVARCHAR(128) = '$(SCHEMA)'
DECLARE @TARGET_SCHEMA NVARCHAR(128) = '$(SCHEMA)'
--
exec sp_COMPARE_SCHEMA TRUE, @SOURCE_DATABASE, @SOURCE_SCHEMA, @TARGET_DATABASE, @TARGET_SCHEMA, '$(METHOD)'
go
--
quit

