--
DECLARE @COMMENT NVARCHAR(128) ='$(METHOD)'
DECLARE @SOURCE_DATABASE NVARCHAR(128) = '$(SCHEMA)$(ID1)'
DECLARE @TARGET_DATABASE NVARCHAR(128) = '$(SCHEMA)$(ID2)'
--
use  $(SCHEMA)$(ID1)
exec sp_COMPARE_SCHEMA TRUE, @SOURCE_DATABASE, 'dbo', @TARGET_DATABASE, 'dbo', @COMMENT, FALSE, 18
go
--
quit