# escape=`
FROM yadamu/svr-2019:vs22
#
RUN New-Item -ItemType "directory" C:\INSTALL; `
    New-Item -ItemType "directory" C:\INSTALL\CU
#
# Unpack SQL Server
#
WORKDIR c:/INSTALL
COPY SQLServer2017-DEV-x64-ENU.exe .
COPY SQLServer2017-DEV-x64-ENU.box .
RUN Start-Process .\SQLServer2017-DEV-x64-ENU.exe  -Wait -ArgumentList """/x:SQLServer2017-DEV-x64-ENU""", """/u"""; `
    Remove-Item SQLServer2017-DEV-x64-ENU.exe; `
    Remove-Item SQLServer2017-DEV-x64-ENU.box
#
# Install SQL Server RTM
#
RUN C:\INSTALL\SQLServer2017-DEV-x64-ENU\SETUP.exe /Q /ACTION=Install /UPDATEENABLED=FALSE /FEATURES=SQLEngine /INSTANCENAME=MSSQLSERVER /SQLSVCACCOUNT='NT AUTHORITY\System' /SQLSYSADMINACCOUNTS='BUILTIN\ADMINISTRATORS' /TCPENABLED=1 /NPENABLED=0 /IACCEPTSQLSERVERLICENSETERMS=1 /SECURITYMODE=SQL /SAPWD="""oracle#1""" 
#
WORKDIR c:/
COPY prepareMounts.ps1 .
RUN Set-Service  -Name """MSSQLSERVER""" -StartupType """Manual"""; `
    Stop-Service -Name """MSSQLSERVER"""; `
    c:\prepareMounts.ps1; `
    Remove-Item c:\prepareMounts.ps1
#
COPY Start.ps1 .
#ENTRYPOINT [ "powershell","c:\\Start.ps1","-ACCEPT_EULA $ENV:ACCEPT_EULA","-SA_PASSWORD $ENV:SA_PASSWORD"]
ENTRYPOINT powershell "c:\\Start.ps1 -ACCEPT_EULA $ENV:ACCEPT_EULA -SA_PASSWORD $ENV:SA_PASSWORD
#ENTRYPOINT ["powershell","wait-event"]
