FROM ubuntu:22.04
RUN apt-get update \
 && apt-get -y install wget gnupg2 software-properties-common net-tools iputils-ping ssh sshpass 
WORKDIR /root
RUN  apt-get install -y virtualbox
COPY Teradata_Database_17.10.02.01_SLES12_SP3_on_VMware_20210603130901.ova .
# COPY Oracle_VM_VirtualBox_Extension_Pack-6.1.34.vbox-extpack .
COPY createTDVM.sh .
copy exec_tdvm_init.sh .
#CMD virtualbox
#CMD sleep 365d
CMD bash -x /root/createTDVM.sh 2>&1 >> /dev/stderr
#
# Usage: 
# docker run --name TDATA17-01 -v TDATA17-01-APPLIANCE:/root/VBox --device /dev/vboxdrv:/dev/vboxdrv --network host teradata/16
#