--
SET SESSION SQL_MODE=ANSI_QUOTES;
--
-- set @ID  = 2;
--
select @ID;
--
select @SCHEMA;
--
SET @STMNT_TXT = CONCAT('DROP DATABASE ','"',@SCHEMA,@ID,'"');
SELECT @STMNT_TXT;
--
PREPARE STMNT_SQL FROM @STMNT_TXT;
EXECUTE STMNT_SQL;
DEALLOCATE PREPARE STMNT_SQL;
--
SET @STMNT_TXT = CONCAT('CREATE DATABASE ','"',@SCHEMA,@ID,'"');
SELECT @STMNT_TXT;
--
PREPARE STMNT_SQL FROM @STMNT_TXT;
EXECUTE STMNT_SQL;
DEALLOCATE PREPARE STMNT_SQL;
--