--
:setvar DATABASE = 'Northwind';
:setvar SCHEMA dbo
DECLARE @SOURCE_DATABASE NVARCHAR(128) = '$(DATABASE)$(ID1)'
DECLARE @TARGET_DATABASE NVARCHAR(128) = '$(DATABASE)$(ID2)'
DECLARE @SOURCE_SCHEMA NVARCHAR(128) = '$(SCHEMA)'
DECLARE @TARGET_SCHEMA NVARCHAR(128) = '$(SCHEMA)'
--
:r sql\SCHEMA_COMPARE.sql
--
:setvar DATABASE = 'AdventureWorks';
:setvar SCHEMA Sales
DECLARE @SOURCE_DATABASE NVARCHAR(128) = '$(DATABASE)$(ID1)'
DECLARE @TARGET_DATABASE NVARCHAR(128) = '$(DATABASE)$(ID2)'
DECLARE @SOURCE_SCHEMA NVARCHAR(128) = '$(SCHEMA)'
DECLARE @TARGET_SCHEMA NVARCHAR(128) = '$(SCHEMA)'
--
:r sql\SCHEMA_COMPARE.sql
--
:setvar SCHEMA Person
DECLARE @SOURCE_DATABASE NVARCHAR(128) = '$(DATABASE)$(ID1)'
DECLARE @TARGET_DATABASE NVARCHAR(128) = '$(DATABASE)$(ID2)'
DECLARE @SOURCE_SCHEMA NVARCHAR(128) = '$(SCHEMA)'
DECLARE @TARGET_SCHEMA NVARCHAR(128) = '$(SCHEMA)'
--
:r sql\SCHEMA_COMPARE.sql
--
:setvar SCHEMA Production
DECLARE @SOURCE_DATABASE NVARCHAR(128) = '$(DATABASE)$(ID1)'
DECLARE @TARGET_DATABASE NVARCHAR(128) = '$(DATABASE)$(ID2)'
DECLARE @SOURCE_SCHEMA NVARCHAR(128) = '$(SCHEMA)'
DECLARE @TARGET_SCHEMA NVARCHAR(128) = '$(SCHEMA)'
--
:r sql\SCHEMA_COMPARE.sql
--
:setvar SCHEMA Purchasing
DECLARE @SOURCE_DATABASE NVARCHAR(128) = '$(DATABASE)$(ID1)'
DECLARE @TARGET_DATABASE NVARCHAR(128) = '$(DATABASE)$(ID2)'
DECLARE @SOURCE_SCHEMA NVARCHAR(128) = '$(SCHEMA)'
DECLARE @TARGET_SCHEMA NVARCHAR(128) = '$(SCHEMA)'
--
:r sql\SCHEMA_COMPARE.sql
--
:setvar SCHEMA HumanResources
DECLARE @SOURCE_DATABASE NVARCHAR(128) = '$(DATABASE)$(ID1)'
DECLARE @TARGET_DATABASE NVARCHAR(128) = '$(DATABASE)$(ID2)'
DECLARE @SOURCE_SCHEMA NVARCHAR(128) = '$(SCHEMA)'
DECLARE @TARGET_SCHEMA NVARCHAR(128) = '$(SCHEMA)')
--
:r sql\SCHEMA_COMPARE.sql
--
:setvar DATABASE = 'AdventureWorksDW';
:setvar SCHEMA dbo
DECLARE @SOURCE_DATABASE NVARCHAR(128) = '$(DATABASE)$(ID1)'
DECLARE @TARGET_DATABASE NVARCHAR(128) = '$(DATABASE)$(ID2)'
DECLARE @SOURCE_SCHEMA NVARCHAR(128) = '$(SCHEMA)'
DECLARE @TARGET_SCHEMA NVARCHAR(128) = '$(SCHEMA)'
--
:r sql\SCHEMA_COMPARE.sql
--
quit

