--
DECLARE @SOURCE_DATABASE NVARCHAR(128) = '$(DATABASE)'
DECLARE @TARGET_DATABASE NVARCHAR(128) = '$(DATABASE)'
--
DECLARE @SOURCE_SCHEMA NVARCHAR(128) = '$(SCHEMA)$(ID1)'
DECLARE @TARGET_SCHEMA NVARCHAR(128) = '$(SCHEMA)$(ID2)'
--
:r sql\SCHEMA_COMPARE.sql
--
quit