--
--
:setvar SCHEMA "HR"
DECLARE @SOURCE_DATABASE NVARCHAR(128) = '$(DATABASE)'
DECLARE @TARGET_DATABASE NVARCHAR(128) = '$(DATABASE)'
DECLARE @SOURCE_SCHEMA NVARCHAR(128) = '$(SCHEMA)$(ID1)'
DECLARE @TARGET_SCHEMA NVARCHAR(128) = '$(SCHEMA)$(ID2)'
--
exec sp_COMPARE_SCHEMA @SOURCE_DATABASE, @SOURCE_SCHEMA, @TARGET_DATABASE, @TARGET_SCHEMA, '$(METHOD)'
go
--
--
:setvar SCHEMA "SH"
DECLARE @SOURCE_DATABASE NVARCHAR(128) = '$(DATABASE)'
DECLARE @TARGET_DATABASE NVARCHAR(128) = '$(DATABASE)'
DECLARE @SOURCE_SCHEMA NVARCHAR(128) = '$(SCHEMA)$(ID1)'
DECLARE @TARGET_SCHEMA NVARCHAR(128) = '$(SCHEMA)$(ID2)'
--
exec sp_COMPARE_SCHEMA @SOURCE_DATABASE, @SOURCE_SCHEMA, @TARGET_DATABASE, @TARGET_SCHEMA, '$(METHOD)'
go
--
--
:setvar SCHEMA "OE"
DECLARE @SOURCE_DATABASE NVARCHAR(128) = '$(DATABASE)'
DECLARE @TARGET_DATABASE NVARCHAR(128) = '$(DATABASE)'
DECLARE @SOURCE_SCHEMA NVARCHAR(128) = '$(SCHEMA)$(ID1)'
DECLARE @TARGET_SCHEMA NVARCHAR(128) = '$(SCHEMA)$(ID2)'
--
exec sp_COMPARE_SCHEMA @SOURCE_DATABASE, @SOURCE_SCHEMA, @TARGET_DATABASE, @TARGET_SCHEMA, '$(METHOD)'
go
--
--
:setvar SCHEMA "PM"
DECLARE @SOURCE_DATABASE NVARCHAR(128) = '$(DATABASE)'
DECLARE @TARGET_DATABASE NVARCHAR(128) = '$(DATABASE)'
DECLARE @SOURCE_SCHEMA NVARCHAR(128) = '$(SCHEMA)$(ID1)'
DECLARE @TARGET_SCHEMA NVARCHAR(128) = '$(SCHEMA)$(ID2)'
--
exec sp_COMPARE_SCHEMA @SOURCE_DATABASE, @SOURCE_SCHEMA, @TARGET_DATABASE, @TARGET_SCHEMA, '$(METHOD)'
go
--
:setvar SCHEMA "IX"
DECLARE @SOURCE_DATABASE NVARCHAR(128) = '$(DATABASE)'
DECLARE @TARGET_DATABASE NVARCHAR(128) = '$(DATABASE)'
DECLARE @SOURCE_SCHEMA NVARCHAR(128) = '$(SCHEMA)$(ID1)'
DECLARE @TARGET_SCHEMA NVARCHAR(128) = '$(SCHEMA)$(ID2)'
--
exec sp_COMPARE_SCHEMA @SOURCE_DATABASE, @SOURCE_SCHEMA, @TARGET_DATABASE, @TARGET_SCHEMA, '$(METHOD)'
go
--
:setvar SCHEMA "BI"
DECLARE @SOURCE_DATABASE NVARCHAR(128) = '$(DATABASE)'
DECLARE @TARGET_DATABASE NVARCHAR(128) = '$(DATABASE)'
DECLARE @SOURCE_SCHEMA NVARCHAR(128) = '$(SCHEMA)$(ID1)'
DECLARE @TARGET_SCHEMA NVARCHAR(128) = '$(SCHEMA)$(ID2)'
--
exec sp_COMPARE_SCHEMA @SOURCE_DATABASE, @SOURCE_SCHEMA, @TARGET_DATABASE, @TARGET_SCHEMA, '$(METHOD)'
go
--
quit

