if [ -z ${MODE+x} ]; then export MODE=DATA_ONLY;fi
export YADAMU_TARGET=`basename $PWD`
. ../unix/initialize.sh $(readlink -f "$0")
sqlplus $DB_USER/$DB_PWD@$DB_CONNECTION @$YADAMU_DB_ROOT/sql/COMPILE_ALL.sql $YADAMU_LOG_PATH
export MODE=DDL_ONLY
export  YADAMU_OUTPUT_PATH=$YADAMU_INPUT_PATH/$MODE
if [ ! -e $YADAMU_OUTPUT_PATH] mkdir $YADAMU_OUTPUT_PATH
sh $YADAMU_SCRIPT_ROOT/unix/export_Oracle.sh $YADAMU_OUTPUT_PATH "" "" $MODE
export MODE=DATA_ONLY
export  YADAMU_OUTPUT_PATH=$YADAMU_INPUT_PATH/$MODE
if [ ! -e $YADAMU_OUTPUT_PATH] mkdir $YADAMU_OUTPUT_PATH
sh $YADAMU_SCRIPT_ROOT/unix/export_Oracle.sh $YADAMU_OUTPUT_PATH "" "" $MODE
export MODE=DDL_AND_DATA
export  YADAMU_OUTPUT_PATH=$YADAMU_INPUT_PATH/$MODE
if [ ! -e $YADAMU_OUTPUT_PATH] mkdir $YADAMU_OUTPUT_PATH
sh $YADAMU_SCRIPT_ROOT/unix/export_Oracle.sh $YADAMU_OUTPUT_PATH "" "" $MODE