version: "2.4"
services:

  ORA2103-01: 
    container_name: ORA2103-01
    image:  yadamu/oracle:21.3.0
    mem_limit: '6gb'
    shm_size: '4gb'
    tmpfs: /dev/shm/:rw,nosuid,nodev,exec,size=4g
    networks:
      - YADAMU-NET
    ports: 
      - "1526:1521"
    environment:
      ORACLE_SID: CDB21300 
      ORACLE_PDB: PDB21300 
      ORACLE_PWD: oracle 
      ORACLE_CHARACTERSET: AL32UTF8
    volumes:
      - YADAMU_01-SHARED:c:\mount
      - ORA2103-01-ADMIN:c:\oracle\admin
      - ORA2103-01-DATA:c:\oracle\oradata
      - ORA2103-01-DIAG:c:\oracle\diag
    restart: always

  ORA1903-01: 
    container_name: ORA1903-01
    image:  yadamu/oracle:19.3.0
    mem_limit: '6gb'
    shm_size: '4gb'
    tmpfs: /dev/shm/:rw,nosuid,nodev,exec,size=4g
    networks:
      - YADAMU-NET
    ports: 
      - "1521:1521"
    environment:
      ORACLE_SID: CDB19300 
      ORACLE_PDB: PDB19300 
      ORACLE_PWD: oracle 
      ORACLE_CHARACTERSET: AL32UTF8
    volumes:
      - YADAMU_01-SHARED:c:\mount
      - ORA1903-01-ADMIN:c:\oracle\admin
      - ORA1903-01-DATA:c:\oracle\oradata
      - ORA1903-01-DIAG:c:\oracle\diag
    restart: always

  ORA1803-01: 
    container_name: ORA1803-01
    image:  yadamu/oracle:18.3.0
    mem_limit: '6gb'
    shm_size: '4gb'
    tmpfs: /dev/shm/:rw,nosuid,nodev,exec,size=4g
    networks:
      - YADAMU-NET
    ports: 
      - "1522:1521"
    environment:
      ORACLE_SID: CDB18300 
      ORACLE_PDB: PDB18300 
      ORACLE_PWD: oracle 
      ORACLE_CHARACTERSET: AL32UTF8
    volumes:
      - YADAMU_01-SHARED:c:\mount
      - ORA1803-01-ADMIN:c:\oracle\admin
      - ORA1803-01-DATA:c:\oracle\oradata
      - ORA1803-01-DIAG:c:\oracle\diag
    restart: always

  ORA1220-01: 
    container_name: ORA1220-01
    image:  yadamu/oracle:12.2.0
    mem_limit: '6gb'
    shm_size: '4gb'
    tmpfs: /dev/shm/:rw,nosuid,nodev,exec,size=4g
    networks:
      - YADAMU-NET
    ports: 
      - "1523:1521"
    environment:
      ORACLE_SID: CDB12200
      ORACLE_PDB: PDB12200 
      ORACLE_PWD: oracle 
      ORACLE_CHARACTERSET: AL32UTF8
    volumes:
      - YADAMU_01-SHARED:c:\mount
      - ORA1220-01-ADMIN:c:\oracle\admin
      - ORA1220-01-DATA:c:\oracle\oradata
      - ORA1220-01-DIAG:c:\oracle\diag
    restart: always

  ORA1120-01: 
    container_name: ORA1120-01
    image:  yadamu/oracle:11.2.0.4
    mem_limit: '6gb'
    shm_size: '4gb'
    tmpfs: /dev/shm/:rw,nosuid,nodev,exec,size=4g
    networks:
      - YADAMU-NET
    ports: 
      - "1525:1521"
    environment:
      ORACLE_SID: ORA11200 
      ORACLE_PDB: ORA11200 
      ORACLE_PWD: oracle 
      ORACLE_CHARACTERSET: AL32UTF8
    volumes:
      - YADAMU_01-SHARED:c:\mount
      - ORA1120-01-ADMIN:c:\oracle\admin
      - ORA1120-01-DATA:c:\oracle\oradata
      - ORA1120-01-DIAG:c:\oracle\diag
    restart: always

  MSSQL17-01: 
    container_name: MSSQL17-01
    image:  yadamu/svr-2016/mssql:2017-CU26
    mem_limit: '6gb'
    shm_size: '4gb'
    networks:
      - YADAMU-NET
    ports: 
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: oracle#1
    volumes:
      - YADAMU_01-SHARED:c:\mount
      - MSSQL17-01-DATA:C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA
      - MSSQL17-01-LOG:C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\LOG
    restart: always

  MSSQL19-01: 
      container_name: MSSQL19-01
      image:  yadamu/mssql:2019-CU13
      mem_limit: '6gb'
      shm_size: '4gb'
      networks:
        - YADAMU-NET
      ports: 
        - "1434:1433"
      environment:
        ACCEPT_EULA: Y
        SA_PASSWORD: oracle#1
      volumes:
        - YADAMU_01-SHARED:c:\mount
        - MSSQL19-01-DATA:C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA
        - MSSQL19-01-LOG:C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\LOG
      restart: always
  
  MSSQL14-01: 
      container_name: MSSQL14-01
      image:  yadamu/svr-2016/mssql:2014
      mem_limit: '6gb'
      shm_size: '4gb'
      networks:
        - YADAMU-NET
      ports: 
        - "1435:1433"
      environment:
        ACCEPT_EULA: Y
        SA_PASSWORD: oracle#1
      volumes:
        - YADAMU_01-SHARED:c:\mount
        - MSSQL14-01-DATA:C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA
        - MSSQL14-01-LOG:C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\LOG
      restart: always
  
  PGSQL14-01: 
    container_name: PGSQL14-01
    image:  yadamu/postgres:14 
    mem_limit: '6gb'
    shm_size: '4gb'
    networks:
      - YADAMU-NET
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: oracle 
    volumes:
      - YADAMU_01-SHARED:c:\mount
      - PGSQL14-01-VOLUME:C:\ProgramData\PostgreSQL\14\data\
    restart: always
    
  MYSQL80-01: 
    container_name: MYSQL80-01
    image:  yadamu/mysql:8
    mem_limit: '6gb'
    shm_size: '4gb'
    networks:
      - YADAMU-NET
    ports: 
      - "3306:3306"
    volumes:
      - YADAMU_01-SHARED:c:\shared
      - MYSQL80-01-VOLUME:C:\ProgramData\MySQL\8.0
    restart: always
  
  MARIA10-01: 
    container_name: MARIA10-01
    image:  yadamu/mariadb:10
    mem_limit: '6gb'
    shm_size: '4gb'
    networks:
      - YADAMU-NET
    ports: 
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: oracle  
    volumes:
      - YADAMU_01-SHARED:c:\shared
      - MARIA10-01-CONF:C:\ProgramData\MariaDB\10\Conf.d
      - MARIA10-01-DATA:C:\ProgramData\MariaDB\10\Data
    restart: always

  MONGO50-01: 
    container_name: MONGO50-01
    image:  yadamu/mongodb:5
    mem_limit: '6gb'
    shm_size: '4gb'
    networks:
      - YADAMU-NET
    ports: 
      - "27017:27017"
    volumes:
      - YADAMU_01-SHARED:c:\shared
      - MONGO50-01-VOLUME:c:\ProgramData\MongoDB\Server\5.0
    restart: always
    
networks: 
  YADAMU-NET:
     name: YADAMU-NET

volumes:
  YADAMU_01-SHARED:
    name: YADAMU_01-SHARED
  ORA2103-01-ADMIN:
  ORA2103-01-DATA:
  ORA2103-01-DIAG:
  ORA1903-01-ADMIN:
  ORA1903-01-DATA:
  ORA1903-01-DIAG:
  ORA1803-01-ADMIN:
  ORA1803-01-DATA:
  ORA1803-01-DIAG:
  ORA1220-01-ADMIN:
  ORA1220-01-DATA:
  ORA1220-01-DIAG:
  ORA1120-01-ADMIN:
  ORA1120-01-DATA:
  ORA1120-01-DIAG:
  MSSQL14-01-DATA:
  MSSQL14-01-LOG:
  MSSQL17-01-DATA:
  MSSQL17-01-LOG:
  MSSQL19-01-DATA:
  MSSQL19-01-LOG:
  PGSQL14-01-VOLUME:
  MYSQL80-01-VOLUME:
  MARIA10-01-CONF:
  MARIA10-01-DATA:
  MONGO50-01-VOLUME:
     
