version: "2.4"
services:

  PGSQL14-01: 
    container_name: PGSQL14-01
    image:  yadamu/postgres:14 
    mem_limit: '16gb'
    shm_size: '4gb'
    networks:
      - YADAMU-NET
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: oracle 
    volumes:
      - YADAMU_01-SHARED:c:\mount
      - PGSQL14-01-DATA:C:\Program Files\PostgreSQL\14\data\
    restart: always
  
networks: 
  YADAMU-NET:
     name: YADAMU-NET
  
volumes:
  YADAMU_01-SHARED:
    name: YADAMU_01-SHARED
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: c:\docker\shared
  PGSQL14-01-DATA:
  
