version: "2.4"
services:

  YADAMU-01:
    container_name: YADAMU-01
    image:  yadamu/regression:latest 
    entrypoint: wait-Event
    mem_limit: '16g'
    isolation: hyperv
    networks:
      - YADAMU-NET
    volumes:
      - YADAMU_01-SHARED:c:\mount
    restart: always
   
networks:
  YADAMU-NET:
     name: YADAMU-NET

volumes:
  YADAMU_01-SHARED:
    name: YADAMU_01-SHARED