FROM postgres:18

ENV LANGUAGE="en_US.UTF-8"
ENV LC_ALL="en_US.UTF-8"
ENV PIP_BREAK_SYSTEM_PACKAGES=1

RUN apt update && \
    apt install -y locales postgis postgresql-18-postgis-3 \
                   postgresql-plpython3-18 \
                   python-is-python3 python3-full \
                   python3-pip pipx python3-lxml && \
    pip install lxml && \
    sed -i -e "s/# $LANGUAGE.*/$LANGUAGE UTF-8/" /etc/locale.gen && \
    grep $LANGUAGE /etc/locale.gen && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=$LANGUAGE