FROM postgres:12
RUN apt update \
 && apt install -y postgis postgresql-12-postgis-3 \ 
 && apt-get update \
 && apt install -y postgresql-plpython3-12 \
 && apt install -y python \
 && apt install -y python3-pip \
 && apt-get install -y python3-lxml \
 && pip3 install lxml \