version: "2.4"
services:

  ORA1903-01: 
    container_name: ORA1903-01
    image:  yadamu/oracle:19.3.0
    isolation: hyperv
    mem_limit: 8192M
    networks:
      - YADAMU-NET
    environment:
      DELAY: 0
      ORACLE_SID: CDB19300 
      ORACLE_PDB: PDB19300 
      ORACLE_PWD: oracle 
      ORACLE_CHARACTERSET: AL32UTF8
    volumes:
      - YADAMU_01-SHARED:c:\mount
      - ORA1903-01-ADMIN:c:\oracle\admin
      - ORA1903-01-DATA:c:\oracle\oradata
      - ORA1903-01-DIAG:c:\oracle\diag
    restart: always

  ORA1803-01: 
    container_name: ORA1803-01
    image:  yadamu/oracle:18.3.0
    isolation: hyperv
    depends_on:
      - ORA1903-01    
    mem_limit: 8192M
    networks:
      - YADAMU-NET
    environment:
      DELAY: 1800
      ORACLE_SID: CDB18300 
      ORACLE_PDB: PDB18300 
      ORACLE_PWD: oracle 
      ORACLE_CHARACTERSET: AL32UTF8
    volumes:
      - YADAMU_01-SHARED:c:\mount
      - ORA1803-01-ADMIN:c:\oracle\admin
      - ORA1803-01-DATA:c:\oracle\oradata
      - ORA1803-01-DIAG:c:\oracle\diag
    restart: always

  ORA1220-01: 
    container_name: ORA1220-01
    image:  yadamu/oracle:12.2.0
    isolation: hyperv
    depends_on:
      - ORA1803-01    
    mem_limit: 8192M
    networks:
      - YADAMU-NET
    environment:
      DELAY: 3600
      ORACLE_SID: CDB12200
      ORACLE_PDB: PDB12200 
      ORACLE_PWD: oracle 
      ORACLE_CHARACTERSET: AL32UTF8
    volumes:
      - YADAMU_01-SHARED:c:\mount
      - ORA1220-01-ADMIN:c:\oracle\admin
      - ORA1220-01-DATA:c:\oracle\oradata
      - ORA1220-01-DIAG:c:\oracle\diag
    restart: always

  ORA1120-01: 
    container_name: ORA1120-01
    image:  yadamu/oracle:11.2.0.4
    isolation: hyperv
    depends_on:
      - ORA1220-01    
    mem_limit: 8192M
    networks:
      - YADAMU-NET
    environment:
      DELAY: 5400
      ORACLE_SID: ORA11200 
      ORACLE_PDB: ORA11200 
      ORACLE_PWD: oracle 
      ORACLE_CHARACTERSET: AL32UTF8
    volumes:
      - YADAMU_01-SHARED:c:\mount
      - ORA1120-01-ADMIN:c:\oracle\admin
      - ORA1120-01-DATA:c:\oracle\oradata
      - ORA1120-01-DIAG:c:\oracle\diag
    restart: always

  MYSQL80-01: 
    container_name: MYSQL80-01
    image:  yadamu/mysql:8
    isolation: hyperv
    depends_on:
      - ORA1120-01    
    mem_limit: 4096M
    networks:
      - YADAMU-NET
    environment:
      DELAY: 7200
    volumes:
      - YADAMU_01-SHARED:c:\shared
      - MYSQL80-01-VOLUME:C:\ProgramData\MySQL\8.0
    restart: always
  
  MARIA10-01: 
    container_name: MARIA10-01
    image:  yadamu/mariadb:10
    isolation: hyperv
    depends_on:
      - MYSQL80-01    
    mem_limit: 4096M
    networks:
      - YADAMU-NET
    environment:
      DELAY: 7200
      MYSQL_ROOT_PASSWORD: oracle  
    volumes:
      - YADAMU_01-SHARED:c:\shared
      - MARIA10-01-CONF:C:\ProgramData\MariaDB\10\Conf.d
      - MARIA10-01-DATA:C:\ProgramData\MariaDB\10\Data
    restart: always

networks: 
  YADAMU-NET:
     name: YADAMU-NET
     external: true
     
volumes:
  YADAMU_01-SHARED:
    name: YADAMU_01-SHARED
  ORA1903-01-ADMIN:
  ORA1903-01-DATA:
  ORA1903-01-DIAG:
  ORA1803-01-ADMIN:
  ORA1803-01-DATA:
  ORA1803-01-DIAG:
  ORA1220-01-ADMIN:
  ORA1220-01-DATA:
  ORA1220-01-DIAG:
  ORA1120-01-ADMIN:
  ORA1120-01-DATA:
  ORA1120-01-DIAG:
  MYSQL80-01-VOLUME:
  MARIA10-01-CONF:
  MARIA10-01-DATA:
     
