set echo on 
spool logs/EXPORT_SCHEMA_ALL.log
--
column TABLE_NAME format A32
column SQL_STATEMENT format A128
column STATUS format A16
column RESULT format A64
-- 
def TARGET_SCHEMA_MODIFIER = 1
--
def SOURCE_SCHEMA = HR
--
def TARGET_SCHEMA = &SOURCE_SCHEMA.&TARGET_SCHEMA_MODIFIER
--
@@CLONE_SCHEMA_SQL &SOURCE_SCHEMA & TARGET_SCHEMA
--
def SOURCE_SCHEMA = SH
--
def TARGET_SCHEMA = &SOURCE_SCHEMA.&TARGET_SCHEMA_MODIFIER
--
@@CLONE_SCHEMA_SQL &SOURCE_SCHEMA & TARGET_SCHEMA
--
cef SOURCE_SCHEMA = OE
--
def TARGET_SCHEMA = &SOURCE_SCHEMA.&TARGET_SCHEMA_MODIFIER
--
@@CLONE_SCHEMA_SQL &SOURCE_SCHEMA & TARGET_SCHEMA
--
def SOURCE_SCHEMA = PM
--
def TARGET_SCHEMA = &SOURCE_SCHEMA.&TARGET_SCHEMA_MODIFIER
--
@@CLONE_SCHEMA_SQL &SOURCE_SCHEMA & TARGET_SCHEMA
--
def SOURCE_SCHEMA = IX
--
def TARGET_SCHEMA = &SOURCE_SCHEMA.&TARGET_SCHEMA_MODIFIER
--
@@CLONE_SCHEMA_SQL &SOURCE_SCHEMA & TARGET_SCHEMA
--
def SOURCE_SCHEMA = BI
--
def TARGET_SCHEMA = &SOURCE_SCHEMA.&TARGET_SCHEMA_MODIFIER
--
@@CLONE_SCHEMA_SQL &SOURCE_SCHEMA & TARGET_SCHEMA
--
quit

