set long 1000000000
set pages 0 lines 256 
set trimspool logs/on
set echo on
column JSON_DOCUMENT format A256
--
ALTER SESSION SET PLSQL_CCFLAGS = 'DEBUG:TRUE'
/
ALTER PACKAGE OBJECT_SERIALIZATION COMPILE
/
show errors
--
ALTER PACKAGE JSON_EXPORT COMPILE
/
VAR JSON_DOCUMENT CLOB
--
VAR OUTPUT_PATH VARCHAR2(2000);
--
declare
  V_RESULT BOOLEAN;
begin
  :OUTPUT_PATH := '/public/export';
  if (not DBMS_XDB.existsResource(:OUTPUT_PATH)) then
    V_RESULT := DBMS_XDB.createFolder(:OUTPUT_PATH);
  end if;
  :OUTPUT_PATH := :OUTPUT_PATH || TO_CHAR(SYS_EXTRACT_UTC(SYSTIMESTAMP),'/IYYY-MM-DD"T"HH24MISS');
  if (not DBMS_XDB.existsResource(:OUTPUT_PATH)) then
    V_RESULT := DBMS_XDB.createFolder(:OUTPUT_PATH);
  end if;
  commit;
end;  
/
DEF SCHEMA = HR
@JSON_EXPORT_TEST
DEF SCHEMA = SH
@JSON_EXPORT_TEST
DEF SCHEMA = BI
@JSON_EXPORT_TEST
DEF SCHEMA = OE
@JSON_EXPORT_TEST
DEF SCHEMA = PM
@JSON_EXPORT_TEST
DEF SCHEMA = IX
@JSON_EXPORT_TEST
--
select COLUMN_VALUE JSON_DOCUMENT from TABLE(JSON_EXPORT.EXPORT_TABLE(USER,'BUILTIN_DATATYPE_TEST'))
/
show errors
--
