version: "2.4"
services:

  YADAMU-SVR:
    container_name: YADAMU-SVC
    image:  yadamu/service
    command: [ "/usr/src/YADAMU/bin/service.sh",
               "CONFIG=src/node/cfg/serviceConfiguration.json",
               "ENCRYPTION=false"]
    mem_limit: '4gb'
    shm_size: '64mb'
    security_opt:
      - seccomp:unconfined
    tmpfs: /dev/shm/:rw,nosuid,nodev,exec,size=4g
    environment:
      TNS_ADMIN: /usr/src/YADAMU
      YADAMU_PASSPHRAS: yabasc
    networks:
      - YADAMU-NET
    ports: 
      - "3000:3000"
    volumes:
      - YADAMU_01-SHARED:/mnt/shared
    restart: always

  # ORA2303-01: 1521
  
  ORA1120-01: 
    container_name: ORA1120-01
    # image:  oracle/database:11.2.0.4-ee
    image:  yadamu/oracle:11.2.0.4
    mem_limit: '10gb'
    shm_size: '4gb'
    security_opt:
      - seccomp:unconfined
    tmpfs: /dev/shm/:rw,nosuid,nodev,exec,size=4g
    networks:
      - YADAMU-NET
    ports: 
      - "15211:1521"
    environment:
      ORACLE_SID: ORA11200 
      ORACLE_PDB: ORA11200 
      ORACLE_PWD: oracle 
      ORACLE_CHARACTERSET: AL32UTF8
    volumes:
      - YADAMU_01-SHARED:/mnt/shared
      - ORA1120-01-DATA:/opt/oracle/admin
      - ORA1120-01-DATA:/opt/oracle/oradata
      - ORA1120-01-DIAG:/opt/oracle/diag
    restart: always

  # ORA1210-01: 15212
  
  ORA1220-01: 
    container_name: ORA1220-01
    # image:  oracle/database:12.2.0.1-ee 
    image:  yadamu/oracle:12.2.0
    mem_limit: '10gb'
    shm_size: '4gb'
    security_opt:
      - seccomp:unconfined
    tmpfs: /dev/shm/:rw,nosuid,nodev,exec,size=4g
    networks:
      - YADAMU-NET
    ports: 
      - "15213:1521"
    environment:
      ORACLE_SID: CDB12200 
      ORACLE_PDB: PDB12200 
      ORACLE_PWD: oracle 
      ORACLE_CHARACTERSET: AL32UTF8
    volumes:
      - YADAMU_01-SHARED:/mnt/shared
      - ORA1220-01-DATA:/opt/oracle/admin
      - ORA1220-01-DATA:/opt/oracle/oradata
      - ORA1220-01-DIAG:/opt/oracle/diag
    restart: always

  ORA1803-01: 
    container_name: ORA1803-01
    # image:  oracle/database:18.3.0-ee
    image:  yadamu/oracle:18.3.0
    mem_limit: '10gb'
    shm_size: '4gb'
    security_opt:
      - seccomp:unconfined
    tmpfs: /dev/shm/:rw,nosuid,nodev,exec,size=4g
    networks:
      - YADAMU-NET
    ports: 
      - "15214:1521"
    environment:
      ORACLE_SID: CDB18300 
      ORACLE_PDB: PDB18300 
      ORACLE_PWD: oracle 
      ORACLE_CHARACTERSET: AL32UTF8
    volumes:
      - YADAMU_01-SHARED:/mnt/shared
      - ORA1803-01-DATA:/opt/oracle/admin
      - ORA1803-01-DATA:/opt/oracle/oradata
      - ORA1803-01-DIAG:/opt/oracle/diag
    restart: always

  ORA1903-01: 
    container_name: ORA1903-01
    # image:  oracle/database:19.3.0-ee
    image:  yadamu/oracle:19.3.0
    mem_limit: '10gb'
    shm_size: '4gb'
    security_opt:
      - seccomp:unconfined
    tmpfs: /dev/shm/:rw,nosuid,nodev,exec,size=4g
    networks:
      - YADAMU-NET
    ports: 
      - "15215:1521"
    environment:
      ORACLE_SID: CDB19300 
      ORACLE_PDB: PDB19300 
      ORACLE_PWD: oracle 
      ORACLE_CHARACTERSET: AL32UTF8
    volumes:
      - YADAMU_01-SHARED:/mnt/shared
      - ORA1903-01-DATA:/opt/oracle/admin
      - ORA1903-01-DATA:/opt/oracle/oradata
      - ORA1903-01-DIAG:/opt/oracle/diag
    restart: always
  
  # ORA2103-01: 15216
  
  MARIA11-01: 
    container_name: MARIA11-01
    image:  mariadb:latest
    mem_limit: '10gb'
    shm_size: '4gb'
    security_opt:
      - seccomp:unconfined
    networks:
      - YADAMU-NET
    ports: 
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: oracle  
    volumes:
      - YADAMU_01-SHARED:/mnt/shared
      - MARIA11-01-CONF:/etc/mysql/conf.d
      - MARIA11-01-DATA:/var/lib/mysql 
    restart: always

  # MARAI10-01: 37071

  MONGO70-01: 
    container_name: MONGO70-01
    image:  mongo:latest 
    mem_limit: '10gb'
    shm_size: '4gb'
    security_opt:
      - seccomp:unconfined
    networks:
      - YADAMU-NET
    ports: 
      - "27017:27017"
    volumes:
      - MONGO70-01-VOLUME:/data/db 
    restart: always

  # MONGO40-01: 27018
  # MONGO50-01: 27019
  # MONGO60-01: 27020

  MSSQL22-01: 
    container_name: MSSQL22-01
    image:  mcr.microsoft.com/mssql/server:2022-latest
    mem_limit: '10gb'
    shm_size: '4gb'
    security_opt:
      - seccomp:unconfined
    networks:
      - YADAMU-NET
    ports: 
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      MSSQL_MEMORY_LIMIT_MB: 16384
      SA_PASSWORD: oracle#1
    volumes:
      - YADAMU_01-SHARED:/mnt/shared
      - MSSQL22-01-VOLUME:/var/opt/mssql
    restart: always

  # MSSQL14-01: 14331

  # MSSQL17-01: 14332

  MSSQL19-01: 
    container_name: MSSQL19-01
    image:  mcr.microsoft.com/mssql/server:2019-latest
    mem_limit: '10gb'
    shm_size: '4gb'
    security_opt:
      - seccomp:unconfined
    networks:
      - YADAMU-NET
    ports: 
      - "14333:1433"
    environment:
      ACCEPT_EULA: Y
      MSSQL_MEMORY_LIMIT_MB: 16384
      SA_PASSWORD: oracle#1
    volumes:
      - YADAMU_01-SHARED:/mnt/shared
      - MSSQL19-01-VOLUME:/var/opt/mssql
    restart: always

  MYSQL81-01: 
    container_name: MYSQL81-01
    image:  mysql:latest
    command: --secure-file-priv=/mnt/shared  
    mem_limit: '10gb'
    shm_size: '4gb'
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    networks:
      - YADAMU-NET
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: oracle  
    volumes:
      - YADAMU_01-SHARED:/mnt/shared
      - MYSQL81-01-VOLUME:/var/lib/mysql 
    restart: always

  # MYSQL80-01: 33061

  PGSQL16-01: 
    container_name: PGSQL16-01
    image:  yadamu/postgres:latest
    mem_limit: '10gb'
    shm_size: '4gb'
    security_opt:
      - seccomp:unconfined
    networks:
      - YADAMU-NET
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: oracle 
    volumes:
      - YADAMU_01-SHARED:/mnt/shared
      - PGSQL16-01-VOLUME:/var/lib/postgresql/data
    restart: always

  # PGSQL11-01: 54321
  # PGSQL12-01: 54322
  # PGSQL13-01: 54323
  # PGSQL14-01: 54324
  # PGSQL15-01: 54325

  VRTCA23-01: 
    container_name: VRTCA23-01
    image:  vertica/vertica-ce:latest 
    mem_limit: '10gb'
    shm_size: '4gb'
    security_opt:
      - seccomp:unconfined
    networks:
     - YADAMU-NET
    ports: 
      - "5433:5433"
      - "5444:5444"
    environment:
      APP_DB_USER: "vertica"
      APP_DB_PASSWORD: "oracle"
      TZ: "Etc/UTC"
    #deploy:
    #  mode: global
    volumes:
      - YADAMU_01-SHARED:/mnt/shared
      - VRTCA23-01-VOLUME:/data
    restart: always    

  # VRTCA09-01: 54331,54441
        
  VRTCA10-01: 
    container_name: VRTCA10-01
    image: vertica/vertica-ce:10.1.1-0
    mem_limit: '10gb'
    shm_size: '4gb'
    networks:
      - YADAMU-NET
    ports: 
      - "54332:5433"
      - "54442:5444"
    environment:
      APP_DB_USER: "vertica"
      APP_DB_PASSWORD: "oracle"
      TZ: "Etc/UTC"
    #deploy:
    #  mode: global
    volumes:
      - YADAMU_01-SHARED:/mnt/shared
      - VRTCA10-01-VOLUME:/data
    restart: always

  # VRTCA11-01: 54333,54443

  # VRTCA12-01: 54334,54444

  MINIO-01: 
    container_name: MINIO-01
    image:  minio/minio 
    command:  server /data --console-address  ":9001"
    networks:
      - YADAMU-NET
    ports: 
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: AKIAIOSFODNN7EXAMPLE
      MINIO_ROOT_PASSWORD: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    volumes:
      - MINIO-01-VOLUME:/data
    restart: always
    
  AZURE-01: 
    container_name: AZURE-01
    image:   mcr.microsoft.com/azure-storage/azurite 
    command: azurite-blob --blobHost 0.0.0.0 --loose --blobPort 10000 
    networks:
      - YADAMU-NET
    ports: 
      - "10000:10000"
    volumes:
      - AZURE-01-VOLUME:/data
    restart: always

  YADAMU-SMB: 
    container_name: YADAMU-SMB
    image:   dperson/samba
    mem_limit: '512mb'
    command: -p -s "work;/mount;yes;no;yes" -n -p
    networks:
      - YADAMU-NET
    ports: 
      - "139:139"
      - "445:445"
      - "137:137/udp"
      - "138:138/udp"
    volumes:
      - YADAMU_01-SHARED:/mount
    restart: always

networks: 
  YADAMU-NET:
     name: YADAMU-NET

volumes:
  YADAMU_01-SHARED:
    name: YADAMU_01-SHARED
  ORA1903-01-DATA:
  ORA1903-01-DIAG:
  ORA1803-01-DATA:
  ORA1803-01-DIAG:
  ORA1220-01-DATA:
  ORA1220-01-DIAG:
  ORA1120-01-DATA:
  ORA1120-01-DIAG:
  MSSQL19-01-VOLUME:
  MSSQL22-01-VOLUME:
  PGSQL16-01-VOLUME:
  MYSQL81-01-VOLUME:
  MARIA11-01-CONF:
  MARIA11-01-DATA:
  MONGO70-01-VOLUME:
  VRTCA10-01-VOLUME:
  VRTCA23-01-VOLUME:
  MINIO-01-VOLUME:
  AZURE-01-VOLUME:
    

    