version: "2.4"

services:

  MARIA10-01: 
    container_name: MARIA10-01
    image:  mariadb:10.9.5
    mem_limit: '10gb'
    shm_size: '4gb'
    security_opt:
      - seccomp:unconfined
    networks:
      - YADAMU-NET
    ports: 
      - "33071:3306"
    environment:
      MYSQL_ROOT_PASSWORD: oracle  
    volumes:
      - YADAMU_01-SHARED:/mnt/shared
      - MARIA10-01-CONF:/etc/mysql/conf.d
      - MARIA10-01-DATA:/var/lib/mysql 
    restart: always
networks: 
  YADAMU-NET:
     name: YADAMU-NET

volumes:
  YADAMU_01-SHARED:
    name: YADAMU_01-SHARED
  MARIA10-01-CONF:
  MARIA10-01-DATA:
    

    