version: "2.4"
services:

 MONGO60-01: 
    container_name: MONGO60-01
    image:  mongo:6 
    mem_limit: '10gb'
    shm_size: '4gb'
    security_opt:
      - seccomp:unconfined
    networks:
      - YADAMU-NET
    ports: 
      - "27020:27017"
    volumes:
      - MONGO60-01-VOLUME:/data/db 
    restart: always

networks: 
  YADAMU-NET:
     name: YADAMU-NET

volumes:
  YADAMU_01-SHARED:
    name: YADAMU_01-SHARED
  MONGO60-01-VOLUME:
    

        