version: "2.4"
services:

  MYSQL80-01: 
    container_name: MYSQL80-01
    image:  mysql:8.0.37
    command: --secure-file-priv=/mnt/shared  
    mem_limit: '10gb'
    shm_size: '4gb'
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    networks:
      - YADAMU-NET
    ports: 
      - "33061:3306"
    environment:
      MYSQL_ROOT_PASSWORD: oracle  
    volumes:
      - YADAMU_01-SHARED:/mnt/shared
      - MYSQL80-01-VOLUME:/var/lib/mysql 
    restart: always
    
networks: 
  YADAMU-NET:
     name: YADAMU-NET

volumes:
  YADAMU_01-SHARED:
    name: YADAMU_01-SHARED
  MYSQL80-01-VOLUME:

