version: "2.4"
services:

  ORA2303-01: 
    container_name: ORA2303-01
    # image:  oracle/database:21.3.0-ee
    image: gvenzl/oracle-free:23
    mem_limit: '16gb'
    security_opt:
      - seccomp:unconfined
    shm_size: '4gb'
    tmpfs: /dev/shm/:rw,nosuid,nodev,exec,size=4g
    networks:
      - YADAMU-NET
    ports: 
      - "1521:1521"
    environment:
      ORACLE_SID: FREE
      ORACLE_PDB: FREEPDB1 
      ORACLE_PWD: oracle 
      ORACLE_CHARACTERSET: AL32UTF8
    volumes:
      - YADAMU_01-SHARED:/mnt/shared
      - ORA2303-01-DATA:/opt/oracle/admin
      - ORA2303-01-DATA:/opt/oracle/oradata
      - ORA2303-01-DIAG:/opt/oracle/diag
    restart: always
    
networks: 
  YADAMU-NET:
     name: YADAMU-NET

volumes:
  YADAMU_01-SHARED:
    name: YADAMU_01-SHARED
  ORA2303-01-DATA:
  ORA2303-01-DIAG:
