version: "2.4"
services:

  PGSQL14-01: 
    container_name: PGSQL14-01
    image:  yadamu/postgres:14
    mem_limit: '12gb'
    security_opt:
      - seccomp:unconfined
    shm_size: '4gb'
    networks:
      - YADAMU-NET
    ports: 
      - "54324:5432"
    environment:
      POSTGRES_PASSWORD: oracle 
    volumes:
      - YADAMU_01-SHARED:/mnt/shared
      - PGSQL14-01-DATA:/var/lib/postgresql/data
    restart: always
 
networks: 
  YADAMU-NET:
     name: YADAMU-NET

volumes:
  YADAMU_01-SHARED:
    name: YADAMU_01-SHARED
  PGSQL14-01-DATA:
    

    