version: "2.4"
services:

  VRTCA23-01: 
    container_name: VRTCA23-01
    image:  vertica/vertica-ce:latest 
    mem_limit: '10gb'
    shm_size: '4gb'
    security_opt:
      - seccomp:unconfined
    networks:
     - YADAMU-NET
    ports: 
      - "5433:5433"
      - "5444:5444"
    environment:
      APP_DB_USER: "vertica"
      APP_DB_PASSWORD: "oracle"
      TZ: "Etc/UTC"
    volumes:
      - YADAMU_01-SHARED:/mnt/shared
      - VRTCA23-01-VOLUME:/data
    restart: always    

  VRTCA10-01: 
    container_name: VRTCA10-01
    image: vertica/vertica-ce:10.1.1-0
    mem_limit: '10gb'
    shm_size: '4gb'
    networks:
      - YADAMU-NET
    ports: 
      - "54332:5433"
      - "54442:5444"
    environment:
      APP_DB_USER: "vertica"
      APP_DB_PASSWORD: "oracle"
      TZ: "Etc/UTC"
    volumes:
      - YADAMU_01-SHARED:/mnt/shared
      - VRTCA10-01-VOLUME:/data
    restart: always

  MINIO-01: 
    container_name: MINIO-01
    image:  minio/minio 
    command:  server /data --console-address  ":9001"
    networks:
      - YADAMU-NET
    ports: 
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: AKIAIOSFODNN7EXAMPLE
      MINIO_ROOT_PASSWORD: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    volumes:
      - MINIO-01-VOLUME:/data
    restart: always
    
  AZURE-01: 
    container_name: AZURE-01
    image:   mcr.microsoft.com/azure-storage/azurite 
    command: azurite-blob --blobHost 0.0.0.0 --loose --blobPort 10000 
    networks:
      - YADAMU-NET
    ports: 
      - "10000:10000"
    volumes:
      - AZURE-01-VOLUME:/data
    restart: always

networks: 
  YADAMU-NET:
     name: YADAMU-NET
     external: true

volumes:
  YADAMU_01-SHARED:
    name: YADAMU_01-SHARED
  VRTCA10-01-VOLUME:
  VRTCA23-01-VOLUME:
  MINIO-01-VOLUME:
  AZURE-01-VOLUME:
    

    