version: "2.4"
services:

  YADAMU-01:
    container_name: YADAMU-01
    image:  yadamu/secure:latest 
    entrypoint: sleep 365d
    mem_limit: '16g'
    security_opt:
     - seccomp:unconfined
    networks:
      - YADAMU-NET
    volumes:
      - YADAMU_01-SHARED:/usr/src/YADAMU/mnt
    restart: always
   
networks: 
  YADAMU-NET:
     name: YADAMU-NET
     
    
volumes:
  YADAMU_01-SHARED:
    name: YADAMU_01-SHARED
  