@set YADAMU_TARGET=Postgres\jTable
@set YADAMU_PARSER=RDBMS
call ..\windows\initialize.bat %~dp0
@set YADAMU_INPUT_PATH=%YADAMU_INPUT_PATH:~0,-7%
psql -U %DB_USER% -h %DB_HOST% -a -f %YADAMU_DB_ROOT%\sql\JSON_IMPORT.sql >> %YADAMU_LOG_PATH%\install\JSON_IMPORT.log
@set SCHEMAVER=1
psql -U %DB_USER% -h %DB_HOST% -a -vID=%SCHEMAVER% -vMETHOD=%YADAMU_PARSER%\ -f %YADAMU_SCRIPT_ROOT%\sql\RECREATE_MSSQL_ALL.sql >>%YADAMU_LOG_PATH%\RECREATE_SCHEMA.log
call %YADAMU_SCRIPT_ROOT%\windows\jTableImport_MSSQL.bat %YADAMU_INPUT_PATH% %SCHEMAVER% ""
call %YADAMU_SCRIPT_ROOT%\windows\export_MSSQL.bat %YADAMU_OUTPUT_PATH% %SCHEMAVER% %SCHEMAVER%
@set SCHEMAVER=2
psql -U %DB_USER% -h %DB_HOST% -a -vID=%SCHEMAVER% -vMETHOD=%YADAMU_PARSER%\ -f %YADAMU_SCRIPT_ROOT%\sql\RECREATE_MSSQL_ALL.sql >>%YADAMU_LOG_PATH%\RECREATE_SCHEMA.log
call %YADAMU_SCRIPT_ROOT%\windows\jTableImport_MSSQL.bat %YADAMU_OUTPUT_PATH% %SCHEMAVER% 1
psql -U %DB_USER% -h %DB_HOST% -q -vID1=1 -vID2=%SCHEMAVER% -vMETHOD=%YADAMU_PARSER%\ -f %YADAMU_SCRIPT_ROOT%\sql\COMPARE_MSSQL_ALL.sql >>%YADAMU_LOG_PATH%\COMPARE_SCHEMA.log
call %YADAMU_SCRIPT_ROOT%\windows\export_MSSQL.bat %YADAMU_OUTPUT_PATH% %SCHEMAVER% %SCHEMAVER%
node %YADAMU_HOME%\utilities\node/compareFileSizes %YADAMU_LOG_PATH% %YADAMU_INPUT_PATH% %YADAMU_OUTPUT_PATH%
node %YADAMU_HOME%\utilities\node/compareArrayContent %YADAMU_LOG_PATH% %YADAMU_INPUT_PATH% %YADAMU_OUTPUT_PATH% false