--
SET SESSION SQL_MODE=ANSI_QUOTES;
--
-- set @SCHEMA = 'HR';
--
select @SCHEMA;
--
SET @STATEMENT = CONCAT('DROP SCHEMA ','"',@SCHEMA,'"');
--
SELECT @STATEMENT;
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;
DEALLOCATE PREPARE STATEMENT;
--
SET @STATEMENT = CONCAT('CREATE SCHEMA ','"',@SCHEMA,'"');
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;
DEALLOCATE PREPARE STATEMENT;
--