--
SET SESSION SQL_MODE=ANSI_QUOTES;
--
select @ID;
--
set @SCHEMA = 'Northwind';
--
SET @STATEMENT = CONCAT('DROP SCHEMA IF EXISTS ','"',@SCHEMA,@ID,'"');
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;
DEALLOCATE PREPARE STATEMENT;
--
SET @STATEMENT = CONCAT('CREATE SCHEMA ','"',@SCHEMA,@ID,'"');
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;
DEALLOCATE PREPARE STATEMENT;
--
set @SCHEMA = 'Sales';
--
SET @STATEMENT = CONCAT('DROP SCHEMA IF EXISTS ','"',@SCHEMA,@ID,'"');
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;
DEALLOCATE PREPARE STATEMENT;
--
SET @STATEMENT = CONCAT('CREATE SCHEMA ','"',@SCHEMA,@ID,'"');
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;

DEALLOCATE PREPARE STATEMENT;
--
set @SCHEMA = 'Person';
--
SET @STATEMENT = CONCAT('DROP SCHEMA IF EXISTS ','"',@SCHEMA,@ID,'"');
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;
DEALLOCATE PREPARE STATEMENT;
--
SET @STATEMENT = CONCAT('CREATE SCHEMA ','"',@SCHEMA,@ID,'"');
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;
DEALLOCATE PREPARE STATEMENT;
--
set @SCHEMA = 'Production';
--
SET @STATEMENT = CONCAT('DROP SCHEMA IF EXISTS ','"',@SCHEMA,@ID,'"');
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;
DEALLOCATE PREPARE STATEMENT;
--
SET @STATEMENT = CONCAT('CREATE SCHEMA ','"',@SCHEMA,@ID,'"');
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;
DEALLOCATE PREPARE STATEMENT;
--
set @SCHEMA = 'Purchasing';
--
SET @STATEMENT = CONCAT('DROP SCHEMA IF EXISTS ','"',@SCHEMA,@ID,'"');
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;
DEALLOCATE PREPARE STATEMENT;
--
SET @STATEMENT = CONCAT('CREATE SCHEMA ','"',@SCHEMA,@ID,'"');
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;
DEALLOCATE PREPARE STATEMENT;
--
set @SCHEMA = 'HumanResources';
--
SET @STATEMENT = CONCAT('DROP SCHEMA IF EXISTS ','"',@SCHEMA,@ID,'"');
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;
DEALLOCATE PREPARE STATEMENT;
--
SET @STATEMENT = CONCAT('CREATE SCHEMA ','"',@SCHEMA,@ID,'"');
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;
DEALLOCATE PREPARE STATEMENT;
--
set @SCHEMA = 'AdventureWorksDW';
--
SET @STATEMENT = CONCAT('DROP SCHEMA IF EXISTS ','"',@SCHEMA,@ID,'"');
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;
DEALLOCATE PREPARE STATEMENT;
--
SET @STATEMENT = CONCAT('CREATE SCHEMA ','"',@SCHEMA,@ID,'"');
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;
DEALLOCATE PREPARE STATEMENT;
--
/*
**
** Dissable Command Line Testing for WorldWideImporters and WorldWideImportersDW
**
*/
quit
--
set @SCHEMA = 'WWI_Application';
--
SET @STATEMENT = CONCAT('DROP SCHEMA IF EXISTS ','"',@SCHEMA,@ID,'"');
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;
DEALLOCATE PREPARE STATEMENT;
--
SET @STATEMENT = CONCAT('CREATE SCHEMA ','"',@SCHEMA,@ID,'"');
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;
DEALLOCATE PREPARE STATEMENT;
--
--
set @SCHEMA = 'WWI_Purchasing';
--
SET @STATEMENT = CONCAT('DROP SCHEMA IF EXISTS ','"',@SCHEMA,@ID,'"');
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;
DEALLOCATE PREPARE STATEMENT;
--
SET @STATEMENT = CONCAT('CREATE SCHEMA ','"',@SCHEMA,@ID,'"');
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;
DEALLOCATE PREPARE STATEMENT;
--
--
set @SCHEMA = 'WWI_Sales';
--
SET @STATEMENT = CONCAT('DROP SCHEMA IF EXISTS ','"',@SCHEMA,@ID,'"');
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;
DEALLOCATE PREPARE STATEMENT;
--
SET @STATEMENT = CONCAT('CREATE SCHEMA ','"',@SCHEMA,@ID,'"');
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;
DEALLOCATE PREPARE STATEMENT;
--
--
set @SCHEMA = 'WWI_Warehouse';
--
SET @STATEMENT = CONCAT('DROP SCHEMA IF EXISTS ','"',@SCHEMA,@ID,'"');
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;
DEALLOCATE PREPARE STATEMENT;
--
SET @STATEMENT = CONCAT('CREATE SCHEMA ','"',@SCHEMA,@ID,'"');
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;
DEALLOCATE PREPARE STATEMENT;
--
--
set @SCHEMA = 'WWI_Dimension';
--
SET @STATEMENT = CONCAT('DROP SCHEMA IF EXISTS ','"',@SCHEMA,@ID,'"');
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;
DEALLOCATE PREPARE STATEMENT;
--
SET @STATEMENT = CONCAT('CREATE SCHEMA ','"',@SCHEMA,@ID,'"');
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;
DEALLOCATE PREPARE STATEMENT;
--
--
set @SCHEMA = 'WWI_Fact';
--
SET @STATEMENT = CONCAT('DROP SCHEMA IF EXISTS ','"',@SCHEMA,@ID,'"');
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;
DEALLOCATE PREPARE STATEMENT;
--
SET @STATEMENT = CONCAT('CREATE SCHEMA ','"',@SCHEMA,@ID,'"');
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;
DEALLOCATE PREPARE STATEMENT;
--
--
set @SCHEMA = 'WWI_Integration';
--
SET @STATEMENT = CONCAT('DROP SCHEMA IF EXISTS ','"',@SCHEMA,@ID,'"');
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;
DEALLOCATE PREPARE STATEMENT;
--
SET @STATEMENT = CONCAT('CREATE SCHEMA ','"',@SCHEMA,@ID,'"');
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;
DEALLOCATE PREPARE STATEMENT;
--
