REPLACE PROCEDURE SP GENERATE_STATEMENTS(P_SOURCE_VENDOR VARCHAR(128), P_SCHEMA VARCHAR(128), P_TABLE_NAME VARCHAR(128), P_SPATIAL_FORMAT VARCHAR(8), P_COLUMNS CLOB, P_DATA_TYPES JSON, P_SIZE_CONSTRAINTS JSON, P_BINARY_JSON BYTEINT)
BEGIN
  DECLARE V_COLUMNS_CLAUSE     CLOB;
  DECLARE V_INSERT_SELECT_LIST CLOB;
  DECLARE V_TARGET_DATA_TYPES  JSON;

  WITH 
    "SOURCE_TABLE_DEFINITIONS" 
    AS ( 
      SELECT C."KEY" IDX
            ,C.VALUE "COLUMN_NAME"
            ,T.VALUE "DATA_TYPE"
            ,CASE
               WHEN S.VALUE IN ('','NULL')
                 THEN NULL
               WHEN INSTR(S.VALUE,',') > 0
                 THEN SUBSTR(S.VALUE,1,INSTR(S.VALUE,',')-1)
               ELSE
                 S.VALUE
             END "DATA_TYPE_LENGTH"
            ,CASE
               WHEN INSTR(S.VALUE,',') > 0
                 THEN SUBSTR(S.VALUE, INSTR(S.VALUE,',')+1)
               ELSE
                 NULL
             END "DATA_TYPE_SCALE"
           FROM JSON_TABLE(CONCAT('[',P_COLUMN_LIST,']'),'$[*]' COLUMNS ("KEY" FOR ORDINALITY, "VALUE" VARCHAR(128) PATH '$')) C
               ,JSON_TABLE(P_DATA_TYPE_LIST,'$[*]' COLUMNS ("KEY" FOR ORDINALITY, "VALUE" VARCHAR(128) PATH '$')) T
               ,JSON_TABLE(P_SIZE_CONSTRAINTS,'$[*]' COLUMNS ("KEY" FOR ORDINALITY, "VALUE" VARCHAR(32) PATH '$')) S
          WHERE (C."KEY" = T."KEY") AND (C."KEY" = S."KEY")
    ),
    "TARGET_TABLE_DEFINITIONS" 
    AS (
      SELECT ST.*
             -- AVOID ERROR 1271 (HY000) AT LINE 37: ILLEGAL MIX OF COLLATIONS FOR OPERATION 'CONCAT'
            ,CAST(MAP_FOREIGN_DATATYPE(P_SOURCE_VENDOR,"DATA_TYPE","DATA_TYPE_LENGTH","DATA_TYPE_SCALE") AS CHAR) TARGET_DATA_TYPE
        FROM "SOURCE_TABLE_DEFINITIONS" ST
    )
	SELECT * FROM TARGET_TABLE_DEFINITIONS;
	
END;  
