# escape=`
FROM yadamu/svr:vs22
#
RUN New-Item -ItemType "directory" C:\INSTALL; `
    New-Item -ItemType "directory" C:\INSTALL\CU
#
WORKDIR c:/INSTALL
#
# Install .NET 3.5SP1 using dism
#
copy sxs-server-2022.zip .
RUN Expand-Archive -Path C:\INSTALL\sxs-server-2022.zip -destinationPath C:\INSTALL; `
    dism /online /enable-feature /featurename:NetFX3 /all /Source:c:\install\sxs /LimitAccess; `
    Remove-Item -Recurse c:\install\sxs; `
    Remove-Item C:\INSTALL\sxs-server-2022.zip
#
# Unpack SQL Server
#
COPY SQLServer2014-SP3-DEV-x64-ENU.zip .
COPY SQLServer2014-Config.ini .							   
RUN Expand-Archive -Path "C:\INSTALL\SQLServer2014-SP3-DEV-x64-ENU.zip" -DestinationPath "C:\INSTALL\SQLServer2014-SP3-DEV-x64-ENU"  
#
# Install SQL Server
#
RUN C:\INSTALL\SQLServer2014-SP3-DEV-x64-ENU\SETUP.exe  /ConfigurationFile=C:\INSTALL\SQLServer2014-Config.ini		
#
WORKDIR c:/
#
RUN  Stop-Service -Name """SQLTELEMETRY"""; `
     Stop-Service -Name """SQLWRITER"""; `
	 Set-Service  -Name """SQLTELEMETRY""" -StartupType """Manual"""; `
     Set-Service  -Name """SQLWRITER""" -StartupType """Manual"""; `
     Compress-Archive -Path """C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA""" -DestinationPath """C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\Data.zip"""; `
     Compress-Archive -Path """C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\Log"""  -DestinationPath """C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\Log.zip"""; `
     Remove-Item -Recurse  """C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA"""; `
     Remove-Item -Recurse  """C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\Log"""# Invoking Setup from a script appears to bypass the issue with "username" cannot be null issue that occurs when setup is invoked directly via the RUN command 
#
RUN .\setup.ps1
##
#RUN $SQLSERVER = GET-SERVICE "MSSQLSERVER"; `
#	$SQLSERVER.Start(@('/T3608','/T3609')); `
#	invoke-sqlcmd -InputFile fixDataFileLocations.sql -username "sa"; `
#	$SQLSERVER.stop(); `
#	$SQLSERVER.Start
##
#RUN Remove-Item SQLServer2014-SP3-DEV-x64-ENU.zip; `
#    Remove-Item setup.ps1; `
#    Remove-Item fixDataFileLocations.sql
##
#WORKDIR c:/
#COPY prepareMounts.ps1 .
#RUN Set-Service  -Name "MSSQLSERVER" -StartupType "Manual"; `
#    Stop-Service -Name "MSSQLSERVER"; `
#    c:\prepareMounts.ps1; `
#    Remove-Item c:\prepareMounts.ps1
#SHELL [ "powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
COPY Start.ps1 .
#ENTRYPOINT [ "powershell","c:\\Start.ps1","-ACCEPT_EULA $ENV:ACCEPT_EULA","-SA_PASSWORD $ENV:SA_PASSWORD"]
ENTRYPOINT powershell "c:\\Start.ps1 -ACCEPT_EULA $ENV:ACCEPT_EULA -SA_PASSWORD $ENV:SA_PASSWORD
#ENTRYPOINT ["powershell","wait-event"]
