--
DECLARE @COMMENT NVARCHAR(128) ='$(METHOD)'
DECLARE @DATETIME_PRECISION INT = $(DATETIME_PRECISION)
DECLARE @SPATIAL_PRECISION INT = $(SPATIAL_PRECISION)
DECLARE @SOURCE_DATABASE NVARCHAR(128) = '$(SCHEMA)$(ID1)'
DECLARE @TARGET_DATABASE NVARCHAR(128) = '$(SCHEMA)$(ID2)'
DECLARE @OPTIONS NVARCHAR(512) = concat('{"emptyStringIsNull": false,  "timestampPrecision": ',@DATETIME_PRECISION,',"spatialPrecision": ',@SPATIAL_PRECISION,',"doublePrecision": 18, "orderedJSON": true, "xmlRule": "DECODE_AND_STRIP_DECLARATION" }');
--
use  $(SCHEMA)$(ID1)
exec sp_COMPARE_SCHEMA TRUE, @SOURCE_DATABASE, 'dbo', @TARGET_DATABASE, 'dbo', @COMMENT, @OPTIONS 
go
--
quit