set SCHEMAID=%1
if not defined YADAMU_HOME set YADAMU_HOME=%CD%
if not defined YADAMU_INSTALL set YADAMU_INSTALL=%YADAMU_HOME%\app\install
if not defined YADAMU_QA_SQL set YADAMU_QA_SQL=%YADAMU_HOME%\qa\sql
set YADAMU_DB=oracle19c
call %YADAMU_INSTALL%\%YADAMU_DB%\env\dbConnection.bat
sqlplus %DB_USER%/%DB_PWD%@%DB_CONNECTION% @%YADAMU_QA_SQL%\oracle\RECREATE_MSSQL_ALL.sql %YADAMU_LOG_PATH%\%YADAMU_DB%  %SCHEMAID%
sqlplus %DB_USER%/%DB_PWD%@%DB_CONNECTION% @%YADAMU_QA_SQL%\oracle\RECREATE_ORACLE_ALL.sql %YADAMU_LOG_PATH%\%YADAMU_DB%  %SCHEMAID%
sqlplus %DB_USER%/%DB_PWD%@%DB_CONNECTION% @%YADAMU_QA_SQL%\oracle\RECREATE_SCHEMA.sql %YADAMU_LOG_PATH%\%YADAMU_DB% jtest%SCHEMAID% 
sqlplus %DB_USER%/%DB_PWD%@%DB_CONNECTION% @%YADAMU_QA_SQL%\oracle\RECREATE_SCHEMA.sql %YADAMU_LOG_PATH%\%YADAMU_DB% sakila%SCHEMAID% 
set YADAMU_DB=oracle18c
call %YADAMU_INSTALL%\%YADAMU_DB%\env\dbConnection.bat
sqlplus %DB_USER%/%DB_PWD%@%DB_CONNECTION% @%YADAMU_QA_SQL%\oracle\RECREATE_MSSQL_ALL.sql %YADAMU_LOG_PATH%  %SCHEMAID%
sqlplus %DB_USER%/%DB_PWD%@%DB_CONNECTION% @%YADAMU_QA_SQL%\oracle\RECREATE_ORACLE_ALL.sql %YADAMU_LOG_PATH%  %SCHEMAID%
sqlplus %DB_USER%/%DB_PWD%@%DB_CONNECTION% @%YADAMU_QA_SQL%\oracle\RECREATE_SCHEMA.sql %YADAMU_LOG_PATH% jtest%SCHEMAID% 
sqlplus %DB_USER%/%DB_PWD%@%DB_CONNECTION% @%YADAMU_QA_SQL%\oracle\RECREATE_SCHEMA.sql %YADAMU_LOG_PATH% sakila%SCHEMAID% 
set YADAMU_DB=oracle12c
call %YADAMU_INSTALL%\%YADAMU_DB%\env\dbConnection.bat
sqlplus %DB_USER%/%DB_PWD%@%DB_CONNECTION% @%YADAMU_QA_SQL%\oracle\RECREATE_MSSQL_ALL.sql %YADAMU_LOG_PATH%  %SCHEMAID%
sqlplus %DB_USER%/%DB_PWD%@%DB_CONNECTION% @%YADAMU_QA_SQL%\oracle\RECREATE_ORACLE_ALL.sql %YADAMU_LOG_PATH%  %SCHEMAID%
sqlplus %DB_USER%/%DB_PWD%@%DB_CONNECTION% @%YADAMU_QA_SQL%\oracle\RECREATE_SCHEMA.sql %YADAMU_LOG_PATH% jtest%SCHEMAID% 
sqlplus %DB_USER%/%DB_PWD%@%DB_CONNECTION% @%YADAMU_QA_SQL%\oracle\RECREATE_SCHEMA.sql %YADAMU_LOG_PATH% sakila%SCHEMAID% 
set YADAMU_DB=oracle11g
call %YADAMU_INSTALL%\%YADAMU_DB%\env\dbConnection.bat
sqlplus %DB_USER%/%DB_PWD%@%DB_CONNECTION% @%YADAMU_QA_SQL%\oracle\RECREATE_MSSQL_ALL.sql %YADAMU_LOG_PATH%  %SCHEMAID%
sqlplus %DB_USER%/%DB_PWD%@%DB_CONNECTION% @%YADAMU_QA_SQL%\oracle\RECREATE_ORACLE_ALL.sql %YADAMU_LOG_PATH%  %SCHEMAID%
sqlplus %DB_USER%/%DB_PWD%@%DB_CONNECTION% @%YADAMU_QA_SQL%\oracle\RECREATE_SCHEMA.sql %YADAMU_LOG_PATH% jtest%SCHEMAID% 
sqlplus %DB_USER%/%DB_PWD%@%DB_CONNECTION% @%YADAMU_QA_SQL%\oracle\RECREATE_SCHEMA.sql %YADAMU_LOG_PATH% sakila%SCHEMAID% 
set YADAMU_DB=mssql
call %YADAMU_INSTALL%\%YADAMU_DB%\env\dbConnection.bat
sqlcmd -U%DB_USER% -P%DB_PWD% -S%DB_HOST% -d%DB_DBNAME% -I -e -vID=%SCHEMAID% -i%YADAMU_QA_SQL%\mssql\RECREATE_MSSQL_ALL.sql >%YADAMU_LOG_PATH%\%YADAMU_DB%\RECREATE_SCHEMA.log
sqlcmd -U%DB_USER% -P%DB_PWD% -S%DB_HOST% -d%DB_DBNAME% -I -e -vID=%SCHEMAID% -i%YADAMU_QA_SQL%\mssql\RECREATE_ORACLE_ALL.sql >>%YADAMU_LOG_PATH%\%YADAMU_DB%\RECREATE_SCHEMA.log
sqlcmd -U%DB_USER% -P%DB_PWD% -S%DB_HOST% -d%DB_DBNAME% -I -e -vMSSQL_SCHEMA=jtest%SCHEMAID% -i%YADAMU_QA_SQL%\mssql\RECREATE_SCHEMA.sql >> %YADAMU_LOG_PATH%\%YADAMU_DB%\RECREATE_SCHEMA.log
sqlcmd -U%DB_USER% -P%DB_PWD% -S%DB_HOST% -d%DB_DBNAME% -I -e -vMSSQL_SCHEMA=sakila%SCHEMAID% -i%YADAMU_QA_SQL%\mssql\RECREATE_SCHEMA.sql >> %YADAMU_LOG_PATH%\%YADAMU_DB%\RECREATE_SCHEMA.log
set YADAMU_DB=mysql
call %YADAMU_INSTALL%\%YADAMU_DB%\env\dbConnection.bat
mysql.exe -u%DB_USER% -p%DB_PWD% -h%DB_HOST% -D%DB_DBNAME% -P%DB_PORT% -v -f --init-command="set @ID='%SCHEMAID%'" <%YADAMU_QA_SQL%\mysql\RECREATE_MSSQL_ALL.sql >%YADAMU_LOG_PATH%\%YADAMU_DB%\RECREATE_SCHEMA.log
mysql.exe -u%DB_USER% -p%DB_PWD% -h%DB_HOST% -D%DB_DBNAME% -P%DB_PORT% -v -f --init-command="set @ID='%SCHEMAID%'" <%YADAMU_QA_SQL%\mysql\RECREATE_ORACLE_ALL.sql >>%YADAMU_LOG_PATH%\%YADAMU_DB%\RECREATE_SCHEMA.log
mysql.exe -u%DB_USER% -p%DB_PWD% -h%DB_HOST% -D%DB_DBNAME% -P%DB_PORT% -v -f --init-command="set @SCHEMA='jtest%SCHEMAID%'" <%YADAMU_QA_SQL%\mysql\RECREATE_SCHEMA.sql >>%YADAMU_LOG_PATH%\%YADAMU_DB%\RECREATE_SCHEMA.log
mysql.exe -u%DB_USER% -p%DB_PWD% -h%DB_HOST% -D%DB_DBNAME% -P%DB_PORT% -v -f --init-command="set @SCHEMA='sakila%SCHEMAID%'" <%YADAMU_QA_SQL%\mysql\RECREATE_SCHEMA.sql >>%YADAMU_LOG_PATH%\%YADAMU_DB%\RECREATE_SCHEMA.log
set YADAMU_DB=mariadb
call %YADAMU_INSTALL%\%YADAMU_DB%\env\dbConnection.bat
mysql.exe -u%DB_USER% -p%DB_PWD% -h%DB_HOST% -D%DB_DBNAME% -P%DB_PORT% -v -f --init-command="set @ID='%SCHEMAID%'" <%YADAMU_QA_SQL%\mariadb\RECREATE_MSSQL_ALL.sql >%YADAMU_LOG_PATH%\%YADAMU_DB%\RECREATE_SCHEMA.log
mysql.exe -u%DB_USER% -p%DB_PWD% -h%DB_HOST% -D%DB_DBNAME% -P%DB_PORT% -v -f --init-command="set @ID='%SCHEMAID%'" <%YADAMU_QA_SQL%\mariadb\RECREATE_ORACLE_ALL.sql >>%YADAMU_LOG_PATH%\%YADAMU_DB%\RECREATE_SCHEMA.log
mysql.exe -u%DB_USER% -p%DB_PWD% -h%DB_HOST% -D%DB_DBNAME% -P%DB_PORT% -v -f --init-command="set @SCHEMA='jtest%SCHEMAID%'" <%YADAMU_QA_SQL%\mariadb\RECREATE_SCHEMA.sql >>%YADAMU_LOG_PATH%\%YADAMU_DB%\RECREATE_SCHEMA.log
mysql.exe -u%DB_USER% -p%DB_PWD% -h%DB_HOST% -D%DB_DBNAME% -P%DB_PORT% -v -f --init-command="set @SCHEMA='sakila%SCHEMAID%'" <%YADAMU_QA_SQL%\mariadb\RECREATE_SCHEMA.sql >>%YADAMU_LOG_PATH%\%YADAMU_DB%\RECREATE_SCHEMA.log
set YADAMU_DB=postgres
call %YADAMU_INSTALL%\%YADAMU_DB%\env\dbConnection.bat
psql -U %DB_USER% -d %DB_DBNAME% -h %DB_HOST% -a -vID=%SCHEMAID% -f %YADAMU_QA_SQL%\%YADAMU_DB%\RECREATE_MSSQL_ALL.sql >%YADAMU_LOG_PATH%\%YADAMU_DB%\RECREATE_SCHEMA.log
psql -U %DB_USER% -d %DB_DBNAME% -h %DB_HOST% -a -vID=%SCHEMAID% -f %YADAMU_QA_SQL%\%YADAMU_DB%\RECREATE_ORACLE_ALL.sql >>%YADAMU_LOG_PATH%\%YADAMU_DB%\RECREATE_SCHEMA.log
psql -U %DB_USER% -d %DB_DBNAME% -h %DB_HOST% -a -vSCHEMA=jtest -vID=%SCHEMAID%  -f %YADAMU_QA_SQL%\postgres\RECREATE_SCHEMA.sql >> %YADAMU_LOG_PATH%\%YADAMU_DB%\RECREATE_SCHEMA.log
psql -U %DB_USER% -d %DB_DBNAME% -h %DB_HOST% -a -vSCHEMA=sakila -vID=%SCHEMAID% -f %YADAMU_QA_SQL%\postgres\RECREATE_SCHEMA.sql >> %YADAMU_LOG_PATH%\%YADAMU_DB%\RECREATE_SCHEMA.log
exit /b