version: "2.4"
services:

  MSSQL17-01: 
    container_name: MSSQL17-01
    image:  yadamu/mssql:2017-CU26
    isolation: hyperv
    mem_limit: 6144M
    networks:
      - YADAMU-NET
    environment:
      DELAY: 0
      ACCEPT_EULA: Y
      SA_PASSWORD: oracle#1
    volumes:
      - YADAMU_01-SHARED:c:\mount
      - MSSQL17-01-DATA:C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA
      - MSSQL17-01-LOG:C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\LOG
    restart: always

  MSSQL19-01: 
      container_name: MSSQL19-01
      image:  yadamu/mssql:2019-CU13
      isolation: hyperv
      mem_limit: 6144M
      networks:
        - YADAMU-NET
      environment:
        DELAY: 0
        ACCEPT_EULA: Y
        SA_PASSWORD: oracle#1
      volumes:
        - YADAMU_01-SHARED:c:\mount
        - MSSQL19-01-DATA:C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA
        - MSSQL19-01-LOG:C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\LOG
      restart: always
  
  PGSQL14-01: 
    container_name: PGSQL14-01
    image:  yadamu/postgres:14 
    isolation: hyperv
    mem_limit: 4096M
    networks:
      - YADAMU-NET
    environment:
      DELAY: 0
      POSTGRES_PASSWORD: oracle 
    volumes:
      - YADAMU_01-SHARED:c:\mount
      - PGSQL14-01-VOLUME:C:\ProgramData\PostgreSQL\14\data\
    restart: always
    
  MONGO50-01: 
    container_name: MONGO50-01
    image:  yadamu/mongodb:5
    isolation: hyperv
    mem_limit: 4096M
    networks:
      - YADAMU-NET
    environment:
      DELAY: 0
    volumes:
      - YADAMU_01-SHARED:c:\shared
      - MONGO50-01-VOLUME:c:\ProgramData\MongoDB\Server\5.0
    restart: always
    
networks: 
  YADAMU-NET:
     name: YADAMU-NET
     external: true

volumes:
  YADAMU_01-SHARED:
    name: YADAMU_01-SHARED
  MSSQL17-01-DATA:
  MSSQL17-01-LOG:
  MSSQL19-01-DATA:
  MSSQL19-01-LOG:
  PGSQL14-01-VOLUME:
  MONGO50-01-VOLUME:
     
