source qa/sh/initialize.sh $BASH_SOURCE[0] $BASH_SOURCE[0] oracle19c/$MODE  upload
export YADAMU_PARSER="SQL"
export SCHEMAVER=1
psql -U $DB_USER -d $DB_DBNAME -h $DB_HOST -a -vID=$SCHEMAVER -vMETHOD=$YADAMU_PARSER -f $YADAMU_SQL_PATH/RECREATE_ORACLE_ALL.sql >>$YADAMU_LOG_PATH/RECREATE_SCHEMA.log
source $YADAMU_SCRIPT_PATH/upload_operations_Oracle.sh $YADAMU_INPUT_PATH $SCHEMAVER ""
source $YADAMU_SCRIPT_PATH/export_operations_Oracle.sh $YADAMU_OUTPUT_PATH $SCHEMAVER $SCHEMAVER $MODE
export SCHEMAVER=2
psql -U $DB_USER -d $DB_DBNAME -h $DB_HOST -a -vID=$SCHEMAVER -vMETHOD=$YADAMU_PARSER -f $YADAMU_SQL_PATH/RECREATE_ORACLE_ALL.sql>>$YADAMU_LOG_PATH/RECREATE_SCHEMA.log
source $YADAMU_SCRIPT_PATH/upload_operations_Oracle.sh $YADAMU_OUTPUT_PATH $SCHEMAVER 1 
psql -U $DB_USER -d $DB_DBNAME -h $DB_HOST -q -vID1=1 -vID2=$SCHEMAVER -vMETHOD=$YADAMU_PARSER -f $YADAMU_SQL_PATH/COMPARE_ORACLE_ALL.sql >>$YADAMU_LOG_PATH/COMPARE_SCHEMA.log
source $YADAMU_SCRIPT_PATH/export_operations_Oracle.sh $YADAMU_OUTPUT_PATH $SCHEMAVER $SCHEMAVER $MODE 
node $YADAMU_QA_BIN/compareFileSizes $YADAMU_LOG_PATH $YADAMU_INPUT_PATH $YADAMU_OUTPUT_PATH
node $YADAMU_QA_BIN/compareArrayContent $YADAMU_LOG_PATH $YADAMU_INPUT_PATH $YADAMU_OUTPUT_PATH false