version: "2.4"
services:

  ORA2103-01: 
    container_name: ORA2103-01
    # image:  oracle/database:21.3.0-ee
    image:  yadamu/oracle:21.3.0
    mem_limit: '16gb'
    shm_size: '4gb'
    tmpfs: /dev/shm/:rw,nosuid,nodev,exec,size=4g
    networks:
      - YADAMU-NET
    #ports: 
      #- "1526:1521"
    environment:
      ORACLE_SID: CDB21300 
      ORACLE_PDB: PDB21300 
      ORACLE_PWD: oracle 
      ORACLE_CHARACTERSET: AL32UTF8
    volumes:
      - YADAMU_01-SHARED:/mnt/shared
      - ORA2103-01-DATA:/opt/oracle/admin
      - ORA2103-01-DATA:/opt/oracle/oradata
      - ORA2103-01-DIAG:/opt/oracle/diag
    restart: always

  VRTCA10-01: 
    container_name: VRTCA10-01
    image: vertica/vertica-ce:10.1.1-0
    mem_limit: '16gb'
    shm_size: '4gb'
    networks:
      - YADAMU-NET
    #ports: 
      #- "5434:5433"
      #- "5445:5444"
    environment:
      APP_DB_USER: "vertica"
      APP_DB_PASSWORD: "oracle"
      TZ: "Etc/UTC"
    #deploy:
    #  mode: global
    volumes:
      - YADAMU_01-SHARED:/mnt/shared
      - VRTCA10-01-VOLUME:/data
    restart: always

  VRTCA11-01: 
    container_name: VRTCA11-01
    image:  vertica/vertica-ce:latest 
    mem_limit: '16gb'
    shm_size: '4gb'
    networks:
     - YADAMU-NET
    #ports: 
      #- "5433:5433"
      #- "5444:5444"
    environment:
      APP_DB_USER: "vertica"
      APP_DB_PASSWORD: "oracle"
      TZ: "Etc/UTC"
    #deploy:
    #  mode: global
    volumes:
      - YADAMU_01-SHARED:/mnt/shared
      - VRTCA11-01-VOLUME:/data
    restart: always    
        
  MINIO-01: 
    container_name: MINIO-01
    image:  minio/minio 
    command:  server /data
    networks:
      - YADAMU-NET
    #ports: 
      #- "9000:9000"
    environment:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    volumes:
      - MINIO-01-VOLUME:/data
    restart: always
    
  AZURE-01: 
    container_name: AZURE-01
    image:   mcr.microsoft.com/azure-storage/azurite 
    command: azurite-blob --blobHost 0.0.0.0 --blobPort 10000 --loose
    networks:
      - YADAMU-NET
    #ports: 
      #- "10000:10000"
    volumes:
      - AZURE-01-VOLUME:/data
    restart: always

  YADAMU-SMB: 
    container_name: YADAMU-SMB
    image:   dperson/samba
    mem_limit: '512mb'
    command: -p -s "work;/mount;yes;no;yes" -n -p
    networks:
      - YADAMU-NET
    #ports: 
      #- "139:139"
      #- "445:445"
      #- "137:137/udp"
      #- "138:138/udp"
    volumes:
      - YADAMU_01-SHARED:/mount
    restart: always

networks: 
  YADAMU-NET:
     name: Y_OVERLAY
     #attachable : true

volumes:
  YADAMU_01-SHARED:
    name: YADAMU_01-SHARED
  ORA2103-01-DATA:
  ORA2103-01-DIAG:
  VRTCA10-01-VOLUME:
  VRTCA11-01-VOLUME:
  MINIO-01-VOLUME:
  AZURE-01-VOLUME:
    

    