REM If running manally run from the YADAMU 'home' folder.
if not defined YADAMU_HOME @set YADAMU_HOME=%CD%
@set YADAMU_INSTALL=%YADAMU_HOME%\app\install
@set YADAMU_QA=%YADAMU_HOME%\qa
@set YADAMU_QA_SQL=%YADAMU_QA%\sql
@set YADAMU_LOG_PATH=%YADAMU_HOME%\log
if not exist %YADAMU_LOG_PATH%\ mkdir %YADAMU_LOG_PATH%
@set YADAMU_LOG_PATH=%YADAMU_LOG_PATH%\install_qa
if exist %YADAMU_LOG_PATH%\ rmdir /s /q %YADAMU_LOG_PATH%
@set ORACLE_TERMOUT=OFF
@set YADAMU_DB=oracle19c
mkdir %YADAMU_LOG_PATH%\%YADAMU_DB%
call %YADAMU_INSTALL%\%YADAMU_DB%\env\dbConnection.bat
sqlplus %DB_USER%/%DB_PWD%@%DB_CONNECTION% @%YADAMU_QA_SQL%\oracle\YADAMU_TEST.sql %YADAMU_LOG_PATH%\%YADAMU_DB% %ORACLE_TERMOUT%
@set YADAMU_DB=oracle18c
mkdir %YADAMU_LOG_PATH%\%YADAMU_DB%
call %YADAMU_INSTALL%\%YADAMU_DB%\env\dbConnection.bat
sqlplus %DB_USER%/%DB_PWD%@%DB_CONNECTION% @%YADAMU_QA_SQL%\oracle\YADAMU_TEST.sql %YADAMU_LOG_PATH%\%YADAMU_DB% %ORACLE_TERMOUT%
@set YADAMU_DB=oracle12c
mkdir %YADAMU_LOG_PATH%\%YADAMU_DB%
call %YADAMU_INSTALL%\%YADAMU_DB%\env\dbConnection.bat
sqlplus %DB_USER%/%DB_PWD%@%DB_CONNECTION% @%YADAMU_QA_SQL%\oracle\YADAMU_TEST.sql %YADAMU_LOG_PATH%\%YADAMU_DB% %ORACLE_TERMOUT%
@set YADAMU_DB=oracle11g
mkdir %YADAMU_LOG_PATH%\%YADAMU_DB%
call %YADAMU_INSTALL%\%YADAMU_DB%\env\dbConnection.bat
sqlplus %DB_USER%/%DB_PWD%@%DB_CONNECTION% @%YADAMU_QA_SQL%\oracle\YADAMU_TEST.sql %YADAMU_LOG_PATH%\%YADAMU_DB% %ORACLE_TERMOUT%
@set YADAMU_DB=mssql
mkdir %YADAMU_LOG_PATH%\%YADAMU_DB%
call %YADAMU_INSTALL%\%YADAMU_DB%\env\dbConnection.bat
sqlcmd -U%DB_USER% -P%DB_PWD% -S%DB_HOST% -dmaster -I -e -i%YADAMU_QA_SQL%\mssql\YADAMU_TEST.sql > %YADAMU_LOG_PATH%\%YADAMU_DB%\YADAMU_TEST.log
@set YADAMU_DB=mysql
mkdir %YADAMU_LOG_PATH%\%YADAMU_DB%
call %YADAMU_INSTALL%\%YADAMU_DB%\env\dbConnection.bat
mysql.exe -u%DB_USER% -p%DB_PWD% -h%DB_HOST% -D%DB_DBNAME% -P%DB_PORT% -v -f <%YADAMU_QA_SQL%\mysql\YADAMU_TEST.sql >%YADAMU_LOG_PATH%\%YADAMU_DB%\YADAMU_TEST.log
@set YADAMU_DB=mariadb
mkdir %YADAMU_LOG_PATH%\%YADAMU_DB%
call %YADAMU_INSTALL%\%YADAMU_DB%\env\dbConnection.bat
mysql.exe -u%DB_USER% -p%DB_PWD% -h%DB_HOST% -D%DB_DBNAME% -P%DB_PORT% -v -f <%YADAMU_QA_SQL%\mariadb\YADAMU_TEST.sql >%YADAMU_LOG_PATH%\%YADAMU_DB%\YADAMU_TEST.log
@set YADAMU_DB=postgres
mkdir %YADAMU_LOG_PATH%\%YADAMU_DB%
call %YADAMU_INSTALL%\%YADAMU_DB%\env\dbConnection.bat
psql -U %DB_USER% -d %DB_DBNAME% -h %DB_HOST% -a -f %YADAMU_QA_SQL%\postgres\YADAMU_TEST.sql > %YADAMU_LOG_PATH%\%YADAMU_DB%\YADAMU_TEST.log
