@set YADAMU_TARGET=MySQL\jTable
@set YADAMU_PARSER=RDBMS
call ..\windows\initialize.bat %~dp0
@set YADAMU_INPUT_PATH=%YADAMU_INPUT_PATH:~0,-7%
sqlplus %DB_USER%/%DB_PWD%@%DB_CONNECTION% @%YADAMU_DB_ROOT%\sql\COMPILE_ALL.sql %YADAMU_LOG_PATH%
sqlplus %DB_USER%/%DB_PWD%@%DB_CONNECTION% @%YADAMU_SCRIPT_ROOT%\sql\YADAMU_TEST.sql %YADAMU_LOG_PATH% OFF
@set FILENAME=sakila
@set SCHEMA=sakila
@set SCHEMAVER=1
sqlplus %DB_USER%/%DB_PWD%@%DB_CONNECTION% @%YADAMU_SCRIPT_ROOT%\sql\RECREATE_SCHEMA.sql %YADAMU_LOG_PATH% %SCHEMA%%SCHEMAVER% 
node %YADAMU_DB_ROOT%\node\jTableImport userid=%DB_USER%/%DB_PWD%@%DB_CONNECTION%  file=%YADAMU_INPUT_PATH%\%FILENAME%.json to_user=\"%SCHEMA%%SCHEMAVER%\" mode=%MODE% log_file=%IMPORTLOG%
node %YADAMU_DB_ROOT%\node\export userid=%DB_USER%/%DB_PWD%@%DB_CONNECTION%  file=%YADAMU_OUTPUT_PATH%\%FILENAME%%SCHEMAVER%.json owner=\"%SCHEMA%%SCHEMAVER%\" mode=%MODE% log_file=%EXPORTLOG%
@set SCHEMAVER=2
sqlplus %DB_USER%/%DB_PWD%@%DB_CONNECTION% @%YADAMU_SCRIPT_ROOT%\sql\RECREATE_SCHEMA.sql %YADAMU_LOG_PATH% %SCHEMA%%SCHEMAVER% 
node %YADAMU_DB_ROOT%\node\jTableImport userid=%DB_USER%/%DB_PWD%@%DB_CONNECTION%  file=%YADAMU_OUTPUT_PATH%\%FILENAME%1.json to_user=\"%SCHEMA%%SCHEMAVER%\" mode=%MODE% log_file=%IMPORTLOG%
sqlplus %DB_USER%/%DB_PWD%@%DB_CONNECTION% @%YADAMU_SCRIPT_ROOT%\sql\COMPARE_SCHEMA.sql %YADAMU_LOG_PATH% %SCHEMA% 1 %SCHEMAVER% %YADAMU_PARSER% %MODE%
node %YADAMU_DB_ROOT%\node\export userid=%DB_USER%/%DB_PWD%@%DB_CONNECTION%  file=%YADAMU_OUTPUT_PATH%\%FILENAME%%SCHEMAVER%.json owner=\"%SCHEMA%%SCHEMAVER%\" mode=%MODE% log_file=%EXPORTLOG%
@set SCHEMA=jtest
@set SCHEMAVER=1
@set FILENAME=jsonExample
sqlplus %DB_USER%/%DB_PWD%@%DB_CONNECTION% @%YADAMU_SCRIPT_ROOT%\sql\RECREATE_SCHEMA.sql %YADAMU_LOG_PATH% %SCHEMA%%SCHEMAVER% 
node %YADAMU_DB_ROOT%\node\jTableImport userid=%DB_USER%/%DB_PWD%@%DB_CONNECTION%  file=%YADAMU_INPUT_PATH%\%FILENAME%.json to_user=\"%SCHEMA%%SCHEMAVER%\" mode=%MODE% log_file=%IMPORTLOG%
node %YADAMU_DB_ROOT%\node\export userid=%DB_USER%/%DB_PWD%@%DB_CONNECTION%  file=%YADAMU_OUTPUT_PATH%\%FILENAME%%SCHEMAVER%.json owner=\"%SCHEMA%%SCHEMAVER%\" mode=%MODE% log_file=%EXPORTLOG%
@set SCHEMAVER=2
sqlplus %DB_USER%/%DB_PWD%@%DB_CONNECTION% @%YADAMU_SCRIPT_ROOT%\sql\RECREATE_SCHEMA.sql %YADAMU_LOG_PATH% %SCHEMA%%SCHEMAVER% 
node %YADAMU_DB_ROOT%\node\jTableImport userid=%DB_USER%/%DB_PWD%@%DB_CONNECTION%  file=%YADAMU_OUTPUT_PATH%\%FILENAME%1.json to_user=\"%SCHEMA%%SCHEMAVER%\" mode=%MODE% log_file=%IMPORTLOG%
sqlplus %DB_USER%/%DB_PWD%@%DB_CONNECTION% @%YADAMU_SCRIPT_ROOT%\sql\COMPARE_SCHEMA.sql %YADAMU_LOG_PATH% %SCHEMA% 1 %SCHEMAVER% %YADAMU_PARSER% %MODE%
node %YADAMU_DB_ROOT%\node\export userid=%DB_USER%/%DB_PWD%@%DB_CONNECTION%  file=%YADAMU_OUTPUT_PATH%\%FILENAME%%SCHEMAVER%.json owner=\"%SCHEMA%%SCHEMAVER%\" mode=%MODE% log_file=%EXPORTLOG%
node %YADAMU_HOME%\utilities\node/compareFileSizes %YADAMU_LOG_PATH% %YADAMU_INPUT_PATH% %YADAMU_OUTPUT_PATH%
node %YADAMU_HOME%\utilities\node/compareArrayContent %YADAMU_LOG_PATH% %YADAMU_INPUT_PATH% %YADAMU_OUTPUT_PATH% false