@set YADAMU_TEST_ROOT=%CD%
call :SETYADAMUWORK %YADAMU_TEST_ROOT%
@set YADAMU_SCRIPT_ROOT=%1
call :SETPARENTDIR %YADAMU_SCRIPT_ROOT%
@set YADAMU_SCRIPT_ROOT=%PARENT_PATH%
call :SETPARENTDIR %YADAMU_SCRIPT_ROOT%
@set YADAMU_SCRIPT_ROOT=%PARENT_PATH%
if not defined MODE set MODE=DATA_ONLY
if not defined YADAMU_HOME call :SETYADAMUHOME %YADAMU_SCRIPT_ROOT%
call :SETYADAMUDB %YADAMU_SCRIPT_ROOT%
@set YADAMU_DB_ROOT=%YADAMU_HOME%\%YADAMU_DB%
@set YADAMU_JSON_ROOT=%YADAMU_HOME%\JSON
@set YADAMU_INPUT_PATH=%YADAMU_JSON_ROOT%\%YADAMU_TARGET%
@set YADAMU_WORK_ROOT=%YADAMU_HOME%\work\%YADAMU_WORK_ID%
if not exist %YADAMU_WORK_ROOT%\ mkdir %YADAMU_WORK_ROOT%
@set YADAMU_LOG_ROOT=%YADAMU_WORK_ROOT%\logs
call %YADAMU_HOME%\tests\windows\initializeLogging.bat
@set YADAMU_OUTPUT_PATH=%YADAMU_WORK_ROOT%\JSON
if not exist %YADAMU_OUTPUT_PATH%\ call %YADAMU_HOME%\tests\windows\createOutputFolders.bat %YADAMU_WORK_ROOT%
@set YADAMU_OUTPUT_PATH=%YADAMU_OUTPUT_PATH%\%YADAMU_TARGET%
if exist %YADAMU_OUTPUT_PATH%\ rmdir /s /q %YADAMU_OUTPUT_PATH%
mkdir %YADAMU_OUTPUT_PATH%
call env\dbConnection.bat
SET Y
exit /b

:SETYADAMUDB
@set YADAMU_DB=%~n1
exit /b

:SETYADAMUHOME
call :SETPARENTDIR %1
call :SETPARENTDIR %PARENT_PATH%
@set YADAMU_HOME=%PARENT_PATH%
exit /b

:SETYADAMUWORK
@set YADAMU_WORK_ID=%~n1
exit /b

:SETPARENTDIR
@set PARENT_PATH=%~dp1
@set PARENT_PATH=%PARENT_PATH:~0,-1%
exit /b
