REPLACE FUNCTION MAP_FOREIGN_DATATYPE(P_SOURCE_VENDOR VARCHAR(128), P_DATA_TYPE VARCHAR(128), P_DATA_TYPE_LENGTH INTEGER, P_DATA_TYPE_SCALE INTEGER)
RETURNS VARCHAR(128)
LANGUAGE SQL
DETERMINISTIC
CONTAINS SQL
SQL SECURITY DEFINER
COLLATION INVOKER
INLINE TYPE 1
RETURN CASE
  WHEN P_SOURCE_VENDOR = 'ORACLE' THEN
    CASE
      WHEN P_DATA_TYPE = 'VARCHAR2'  THEN
       'VARCHAR'
     WHEN P_DATA_TYPE = 'NVARCHAR2' THEN
       'VARCHAR'
     WHEN P_DATA_TYPE = 'NUMBER' THEN
       'DECIMAL'
     WHEN P_DATA_TYPE = 'BINARY_FLOAT' THEN
       'DOUBLE PRECISION'
     WHEN P_DATA_TYPE = 'BINARY_DOUBLE' THEN
       'DOUBLE PRECISION'
     WHEN P_DATA_TYPE = 'CLOB' THEN
       'CLOB'
     WHEN P_DATA_TYPE = 'BLOB' THEN
       'BLOB'
     WHEN P_DATA_TYPE = 'NCLOB' THEN
       'CLOB'
     WHEN P_DATA_TYPE = 'XMLTYPE' THEN
       'XML'
     WHEN P_DATA_TYPE = 'TIMESTAMP' THEN
       CASE
         WHEN P_DATA_TYPE_LENGTH > 6 THEN 
		   'TIMESTAMP(6)'
         ELSE 
		   'TIMESTAMP'
       END
     WHEN P_DATA_TYPE = 'BFILE' THEN
       'VARCHAR(2048)'
     WHEN P_DATA_TYPE = 'ROWID' THEN
       'VARCHAR(32)'
     WHEN P_DATA_TYPE = 'RAW' THEN
       'BINARY'
     WHEN P_DATA_TYPE = 'ANYDATA' THEN
       'CLOB'
     WHEN P_DATA_TYPE = '"MDSYS"."SDO_GEOMETRY"' THEN
       'ST_GEOMETRY'
     WHEN (INSTR(P_DATA_TYPE,'TIME ZONE') > 0) THEN
       'TIMESTAMP'
     WHEN (INSTR(P_DATA_TYPE,'INTERVAL') = 1) THEN
       'INTERVAL'
     WHEN (INSTR(P_DATA_TYPE,'XMLTYPE') > 0) THEN
       'XML'
     WHEN (INSTR(P_DATA_TYPE,'"."') > 0) THEN 
       'CLOB'
	 ELSE
       UPPER(P_DATA_TYPE)
  END
END;
