REPLACE PROCEDURE YADAMU.SP_RECREATE_DATABASE ( IN P_DBNAME VARCHAR(128), IN P_DBSIZE DECIMAL(10), P_DBSPEC VARCHAR(31000))
SQL SECURITY INVOKER
BEGIN
   DECLARE V_SQL_STATEMENT VARCHAR(32000);
   BEGIN
     DECLARE CONTINUE HANDLER FOR SQLSTATE '42000', SQLSTATE '52004' BEGIN END;
     SET V_SQL_STATEMENT = 'DELETE DATABASE ' || P_DBNAME || ' ALL';
     EXECUTE IMMEDIATE V_SQL_STATEMENT;
     SET V_SQL_STATEMENT = 'DROP DATABASE ' || P_DBNAME;
     EXECUTE IMMEDIATE V_SQL_STATEMENT;
   END;

   SET V_SQL_STATEMENT = 'CREATE DATABASE ' || P_DBNAME || ' FROM YADAMU_QA AS PERM = ' || P_DBSIZE || ' ' || NVL(P_DBSPEC,'');
   EXECUTE IMMEDIATE V_SQL_STATEMENT;

   SET V_SQL_STATEMENT = 'GRANT ALL ON ' || P_DBNAME || ' TO DBC WITH GRANT OPTION';
   EXECUTE IMMEDIATE V_SQL_STATEMENT;

END;
--