source qa/sh/initialize.sh $BASH_SOURCE[0] $BASH_SOURCE[0] oracle19c/$MODE  import
export YADAMU_PARSER="CLARINET"
export SCHEMAVER=1
mysql -u$DB_USER -p$DB_PWD -h$DB_HOST -D$DB_DBNAME -P$DB_PORT -v -f --init-command="set @ID=$SCHEMAVER; set @METHOD='$YADAMU_PARSER';" <$YADAMU_SQL_PATH/RECREATE_ORACLE_ALL.sql >>$YADAMU_LOG_PATH/RECREATE_SCHEMA.log
source $YADAMU_SCRIPT_PATH/import_operations_Oracle.sh $YADAMU_INPUT_PATH $SCHEMAVER ""
source $YADAMU_SCRIPT_PATH/export_operations_Oracle.sh $YADAMU_OUTPUT_PATH $SCHEMAVER $SCHEMAVER $MODE
export SCHEMAVER=2
mysql -u$DB_USER -p$DB_PWD -h$DB_HOST -D$DB_DBNAME -P$DB_PORT -v -f --init-command="set @ID=$SCHEMAVER; set @METHOD='$YADAMU_PARSER';" <$YADAMU_SQL_PATH/RECREATE_ORACLE_ALL.sql >>$YADAMU_LOG_PATH/RECREATE_SCHEMA.log
source $YADAMU_SCRIPT_PATH/import_operations_Oracle.sh $YADAMU_OUTPUT_PATH $SCHEMAVER 1 
mysql -u$DB_USER -p$DB_PWD -h$DB_HOST -D$DB_DBNAME -P$DB_PORT --init-command="set @ID1=1; set @ID2=$SCHEMAVER; set @METHOD='$YADAMU_PARSER'" --table <$YADAMU_SQL_PATH/COMPARE_ORACLE_ALL.sql >>$YADAMU_LOG_PATH/COMPARE_SCHEMA.log
source $YADAMU_SCRIPT_PATH/export_operations_Oracle.sh $YADAMU_OUTPUT_PATH $SCHEMAVER $SCHEMAVER $MODE 
node $YADAMU_QA_BIN/compareFileSizes $YADAMU_LOG_PATH $YADAMU_INPUT_PATH $YADAMU_OUTPUT_PATH
node $YADAMU_QA_BIN/compareArrayContent $YADAMU_LOG_PATH $YADAMU_INPUT_PATH $YADAMU_OUTPUT_PATH false