"use strict" 
const fs = require('fs');
const path = require('path');

const YadamuDBI = require('../../common/yadamuDBI.js');
const FileWriter = require('./fileWriter.js');
const JSONParser = require('./jsonParser.js');
const EventManager = require('./eventManager.js')
/*
**
** YADAMU Database Inteface class skeleton
**
*/

class FileDBI extends YadamuDBI {

  getConnectionProperties() {
    return {}
  }
  
  exportComplete(message) {
	this.eventManager.exportComplete(message);
  }
  
  closeInputStream() {      
    this.inputStream.close();
  }

  closeOutputStream() {
     return new Promise((resolve,reject) => {
      this.outputStream.on('finish',() => { resolve() });
      this.outputStream.close();
    })

  }
  
  // Override YadamuDBI - Any DDL is considered valid and written to the export file.
  
  isValidDDL() {
    return true;
  }
  
  // Override YadamuDBI
  
  isDatabase() {
    return false;
  }
  
  // Override YadamuDBI

  objectMode() {
     return false;  
  }

  async getMetadata() {
	return []
  }
  
  async getSystemInformation() {
	return {}
  }

  async setSystemInformation(systemInformation) {
	super.setSystemInformation(systemInformation) 
    if (this.outputStream !== undefined) {
      this.outputStream.write(`"systemInformation":${JSON.stringify(this.systemInformation)}`);
	}
  }
  
  setMetadata(metadata) {
	super.setMetadata(metadata)
    if (this.outputStream !== undefined) {
  	  this.outputStream.write(',');
      this.outputStream.write(`"metadata":${JSON.stringify(this.metadata)}`);
	}
  }
 
  get DATABASE_VENDOR()    { return 'FILE' };
  get SOFTWARE_VENDOR()    { return 'N/A' };
  get SPATIAL_FORMAT()     { return this.spatialFormat };
  get DEFAULT_PARAMETERS() { return this.yadamu.getYadamuDefaults().file }
    
  async releaseConnection() {
  }
  
  constructor(yadamu,defaults) {
	defaults = defaults === undefined ? yadamu.getYadamuDefaults().file : defaults 
    super(yadamu,yadamu.getYadamuDefaults().file )
    this.outputStream = undefined;
    this.inputStream = undefined;
	this.ddl = undefined;
    this.firstTable = true;
  }

  generateStatementCache() {
	this.statementCache = {}
  }
      
  async executeDDL(ddl) {
    this.outputStream.write(',');
    this.outputStream.write(`"ddl":${JSON.stringify(ddl)}`);
  }

  async initialize() {
    super.initialize(false);
    this.spatialFormat = this.parameters.SPATIAL_FORMAT ? this.parameters.SPATIAL_FORMAT : super.SPATIAL_FORMAT
  }

  async initializeExport() {
	// this.yadamuLogger.trace([this.constructor.name],`initializeExport()`)
	// For FileDBI Export is Reading data from the file system..
	super.initializeExport();
  }

  async finalizeExport() {
 	// this.yadamuLogger.trace([this.constructor.name,],'finalizeExport()')
	this.closeInputStream()
  }
  
  async initializeImport() {
	// this.yadamuLogger.trace([this.constructor.name],`initializeImport()`)
	// For FileDBI Import is Writing data to the file system.
	super.initializeImport()
    const exportFilePath = path.resolve(this.parameters.FILE);
    this.outputStream = fs.createWriteStream(exportFilePath);
    this.yadamuLogger.info([this.DATABASE_VENDOR],`Writing file "${exportFilePath}".`)
	this.outputStream.write(`{`)
  }

  async initializeData() {
    this.outputStream.write(',');
    this.outputStream.write('"data":{'); 
  }
  
  async finalizeData() {
	// this.yadamuLogger.trace([this.constructor.name],`finalizeData()`)
	this.outputStream.write('}');
  }  
  
  async finalizeImport() {
    // this.yadamuLogger.trace([this.constructor.name],`finalizeImport()`)
	this.outputStream.write('}');
  }
  
  async finalize() {
  }


  /*
  **
  **  Abort the database connection.
  **
  */

  async abort() {

    try {
      if (this.inputStream !== undefined) {
        await this.closeInputStream()
	  }
    } catch (err) {
      this.yadamuLogger.handleException([`${this.DATABASE_VENDOR}`,'ABORT','InputStream'],err);
    }
	 
    try {
      if (this.outputStream !== undefined) {
        await this.closeOutputStream()
	  }
    } catch (err) {
      this.yadamuLogger.handleException([`${this.DATABASE_VENDOR}`,'ABORT','OutputStream'],err);
    }
  }

  /*
  **
  **  Generate a set of DDL operations from the metadata generated by an Export operation
  **
  */
  
      
  async generateStatementCache(schema,executeDDL) {

    this.statementCache = []
  }


  async getDDLOperations() {
    return []
  }
  
  async getSchemaInfo(schema) {
    return []
  }
  
  getTableInfo(tableName) {
	return { tableName: tableName}
  }

  createParser(tableInfo,objectMode) {
 	// this.yadamuLogger.trace([this.constructor.name,],'createParser()')
	const jsonParser = new JSONParser(this.yadamuLogger,this.parameters.MODE);
    return jsonParser
  }  
  
  getInputStream() {
 	// this.yadamuLogger.trace([this.constructor.name,],'getInputStream()')
	const importFilePath = path.resolve(this.parameters.FILE);
    const stats = fs.statSync(importFilePath)
    const fileSizeInBytes = stats.size
    this.yadamuLogger.info([this.DATABASE_VENDOR],`Processing file "${importFilePath}". Size ${fileSizeInBytes} bytes.`)
    this.inputStream = fs.createReadStream(importFilePath);
	return this.inputStream;
  }
  
  getEventStream(inputCallback,outputCallback) {
    this.getInputStream()
	this.inputStream.on('error',inputCallback)
	this.eventManager = new EventManager(this.yadamuLogger,outputCallback)
	return this.inputStream.pipe(this.createParser()).pipe(this.eventManager,{end: false})
  }

  getOutputStream(primary) {
    // Override parent method to allow output stream to be passed to worker
    // return super.getOutputStream(FileWriter,primary)
	 return new FileWriter(this,primary,this.status,this.yadamuLogger,this.outputStream)
  }
  
}

module.exports = FileDBI
