# escape=`
FROM yadamu/svr:vs22 
#
ADD https://fastdl.mongodb.org/windows/mongodb-windows-x86_64-7.0.2-signed.msi .
RUN start-process msiexec.exe -Wait -ArgumentList "/l*v", "mdbinstall.log", "/qb", "/i", """mongodb-windows-x86_64-7.0.2-signed.msi SHOULD_INSTALL_COMPASS=""0"" ADDLOCAL=""ServerNoService"""""; `
    Remove-Item mongodb-windows-x86_64-7.0.2-signed.msi; `
    [Environment]::SetEnvironmentVariable("""Path""", """c:\Program Files\MongoDB\Server\7.0\bin;""" +  $env:Path,"""Machine"""); 
#
WORKDIR C:/Program Files/MongoDB/Server/7.0/
COPY mongod.cfg bin
#
#
# Mongosh
# 
ADD https://downloads.mongodb.com/compass/mongosh-1.1.2-x64.msi .
RUN Start-Process MsiExec.exe  -Wait -ArgumentList """/quiet""", """/passive""", """/qn""", """/i""", """mongosh-1.1.2-x64.msi"""; `
    Remove-Item .\mongosh-1.1.2-x64.msi;
#
WORKDIR c:/
COPY Start.ps1 .
ENTRYPOINT ["powershell","c:\\Start.ps1"]
#ENTRYPOINT ["powershell","wait-event"]
