export DB_USER="${MARIADB_USER:-root}"
export DB_PWD="${MARIADB_PWD:-oracle}"
export DB_HOST="${MARIADB_HOST:-localhost}"
export DB_PORT="${MARIADB_PORT:-3306}"
export DB_DBNAME="${MARIADB_DBNAME:-mysql}"