INITLOGGING()
export SCHVER=1
source $YADAMU_TEST_HOME/oracle/env/dbConnection.sh
sqlplus $DB_USER/$DB_PWD@$DB_CONNECTION @$YADAMU_HOME/oracle/sql/COMPILE_ALL.sql $YADAMU_LOG_PATH
sqlplus $DB_USER/$DB_PWD@$DB_CONNECTION @$YADAMU_TEST_HOME/oracle/sql/RECREATE_MSSQL_ALL.sql $YADAMU_LOG_PATH 1 Clarinet
sqlplus $DB_USER/$DB_PWD@$DB_CONNECTION @$YADAMU_TEST_HOME/oracle/sql/RECREATE_ORACLE_ALL.sql $YADAMU_LOG_PATH 1 Clarinet DDL_AND_DATA
sqlplus $DB_USER/$DB_PWD@$DB_CONNECTION @$YADAMU_TEST_HOME/oracle/sql/RECREATE_SCHEMA.sql $YADAMU_LOG_PATH JTEST1 Clarinet
sqlplus $DB_USER/$DB_PWD@$DB_CONNECTION @$YADAMU_TEST_HOME/oracle/sql/RECREATE_SCHEMA.sql $YADAMU_LOG_PATH SAKILA1 Clarinet
source $YADAMU_TEST_HOME/mssql/env/dbConnection.sh
export ID=1
export METHOD=CLARINET
export DATABASE=$DB_DBNAME
sqlcmd -U$DB_USER -P$DB_PWD -S$DB_HOST -d$DB_DBNAME -I -e -i$YADAMU_HOME/mssql/sql/JSON_IMPORT.sql > $YADAMU_LOG_PATH/MSSQL_JSON_IMPORT.log
sqlcmd -U$DB_USER -P$DB_PWD -S$DB_HOST -d$DB_DBNAME -I -e -i$YADAMU_TEST_HOME/mssql/sql/RECREATE_MSSQL_ALL.sql >$YADAMU_LOG_PATH/MSSQL_RECREATE_SCHEMA.log
sqlcmd -U$DB_USER -P$DB_PWD -S$DB_HOST -d$DB_DBNAME -I -e -i$YADAMU_TEST_HOME/mssql/sql/RECREATE_ORACLE_ALL.sql >>$YADAMU_LOG_PATH/MSSQL_RECREATE_SCHEMA.log
export MSSQL_SCHEMA=AdventureWorksAll
sqlcmd -U$DB_USER -P$DB_PWD -S$DB_HOST -d$DB_DBNAME -I -e -i$YADAMU_TEST_HOME/mssql/sql/RECREATE_SCHEMA.sql >> $YADAMU_LOG_PATH/MSSQL_RECREATE_SCHEMA.log
export MSSQL_SCHEMA=JTEST
sqlcmd -U$DB_USER -P$DB_PWD -S$DB_HOST -d$DB_DBNAME -I -e -i$YADAMU_TEST_HOME/mssql/sql/RECREATE_SCHEMA.sql >> $YADAMU_LOG_PATH/MSSQL_RECREATE_SCHEMA.log
export MSSQL_SCHEMA=SAKILA
sqlcmd -U$DB_USER -P$DB_PWD -S$DB_HOST -d$DB_DBNAME -I -e -i$YADAMU_TEST_HOME/mssql/sql/RECREATE_SCHEMA.sql >> $YADAMU_LOG_PATH/MSSQL_RECREATE_SCHEMA.log
source $YADAMU_TEST_HOME/mysql/env/dbConnection.sh
mysql.exe -u$DB_USER -p$DB_PWD -h$DB_HOST -D$DB_DBNAME -P$DB_PORT -v -f <$YADAMU_HOME/mysql/sql/JSON_IMPORT.sql >$YADAMU_LOG_PATH/MYSQL_JSON_IMPORT.log
mysql.exe -u$DB_USER -p$DB_PWD -h$DB_HOST -D$DB_DBNAME -P$DB_PORT -v -f --init-command="set @ID='1'; set @METHOD='Clarinet'" <$YADAMU_TEST_HOME/mysql/sql/RECREATE_MSSQL_ALL.sql >$YADAMU_LOG_PATH/MYSQL_RECREATE_SCHEMA.log
mysql.exe -u$DB_USER -p$DB_PWD -h$DB_HOST -D$DB_DBNAME -P$DB_PORT -v -f --init-command="set @ID='1'; set @METHOD='Clarinet';"<$YADAMU_TEST_HOME/mysql/sql/RECREATE_ORACLE_ALL.sql >>$YADAMU_LOG_PATH/MYSQL_RECREATE_SCHEMA.log
mysql.exe -u$DB_USER -p$DB_PWD -h$DB_HOST -D$DB_DBNAME -P$DB_PORT -v -f --init-command="set @SCHEMA='JTEST'; set @ID='1'; set @METHOD='Clarinet'" <$YADAMU_TEST_HOME/mariadb/sql/RECREATE_SCHEMA.sql >>$YADAMU_LOG_PATH/MYSQL_RECREATE_SCHEMA.log
mysql.exe -u$DB_USER -p$DB_PWD -h$DB_HOST -D$DB_DBNAME -P$DB_PORT -v -f --init-command="set @SCHEMA='SAKILA'; set @ID='1'; set @METHOD='Clarinet'" <$YADAMU_TEST_HOME/mariadb/sql/RECREATE_SCHEMA.sql >>$YADAMU_LOG_PATH/MYSQL_RECREATE_SCHEMA.log
source $YADAMU_TEST_HOME/mariadb/env/dbConnection.sh
mysql.exe -u$DB_USER -p$DB_PWD -h$DB_HOST -D$DB_DBNAME -P$DB_PORT -v -f <$YADAMU_HOME/mariadb/sql/JSON_IMPORT.sql >$YADAMU_LOG_PATH/MARIADB_JSON_IMPORT.log
mysql.exe -u$DB_USER -p$DB_PWD -h$DB_HOST -D$DB_DBNAME -P$DB_PORT -v -f --init-command="set @ID='1'; set @METHOD='Clarinet'" <$YADAMU_TEST_HOME/mysql/sql/RECREATE_MSSQL_ALL.sql >$YADAMU_LOG_PATH/MARIADB_RECREATE_SCHEMA.log
mysql.exe -u$DB_USER -p$DB_PWD -h$DB_HOST -D$DB_DBNAME -P$DB_PORT -v -f --init-command="set @ID='1'; set @METHOD='Clarinet';"<$YADAMU_TEST_HOME/mysql/sql/RECREATE_ORACLE_ALL.sql >>$YADAMU_LOG_PATH/MARIADB_RECREATE_SCHEMA.log
mysql.exe -u$DB_USER -p$DB_PWD -h$DB_HOST -D$DB_DBNAME -P$DB_PORT -v -f --init-command="set @SCHEMA='JTEST'; set @ID='1'; set @METHOD='Clarinet'" <$YADAMU_TEST_HOME/mariadb/sql/RECREATE_SCHEMA.sql >>$YADAMU_LOG_PATH/MARIADB_RECREATE_SCHEMA.log
mysql.exe -u$DB_USER -p$DB_PWD -h$DB_HOST -D$DB_DBNAME -P$DB_PORT -v -f --init-command="set @SCHEMA='SAKILA'; set @ID='1'; set @METHOD='Clarinet'" <$YADAMU_TEST_HOME/mariadb/sql/RECREATE_SCHEMA.sql >>$YADAMU_LOG_PATH/MARIADB_RECREATE_SCHEMA.log
source $YADAMU_TEST_HOME/postgres/env/dbConnection.sh
psql -U $DB_USER -d $DB_DBNAME -h $DB_HOST -a -f $YADAMU_HOME/postgres/sql/JSON_IMPORT.sql > $YADAMU_LOG_PATH/POSTGRES_JSON_IMPORT.log
psql -U $DB_USER -d $DB_DBNAME -h $DB_HOST -a -vID=1 -vMETHOD=Clarinet -f $YADAMU_TEST_HOME/postgres/sql/RECREATE_MSSQL_ALL.sql >$YADAMU_LOG_PATH/POSTGRES_RECREATE_SCHEMA.log
psql -U $DB_USER -d $DB_DBNAME -h $DB_HOST -a -vID=1 -vMETHOD=Clarinet -f $YADAMU_TEST_HOME/postgres/sql/RECREATE_ORACLE_ALL.sql >>$YADAMU_LOG_PATH/POSTGRES_RECREATE_SCHEMA.log
psql -U $DB_USER -d $DB_DBNAME -h $DB_HOST -a -vSCHEMA=JTEST -vID=1 -vMETHOD=Clarinet -f $YADAMU_TEST_HOME/postgres/sql/RECREATE_SCHEMA.sql >> $YADAMU_LOG_PATH/POSTGRES_RECREATE_SCHEMA.log
psql -U $DB_USER -d $DB_DBNAME -h $DB_HOST -a -vSCHEMA=SAKILA -vID=1 -vMETHOD=Clarinet -f $YADAMU_TEST_HOME/postgres/sql/RECREATE_SCHEMA.sql >> $YADAMU_LOG_PATH/POSTGRES_RECREATE_SCHEMA.log
exit /b

INITLOGGING()
{
export YADAMU_LOG=$YADAMU_HOME/logs
mkdir $YADAMU_LOG
export YADAMU_LOG=$YADAMU_LOG/$(date --utc +%FT%H%M%S.%3NZ)
rmdir /q /s $YADAMU_LOG
mkdir $YADAMU_LOG
mkdir $YADAMU_LOG/install
export LOGDIR=$YADAMU_LOG
}