--
SET SESSION SQL_MODE=ANSI_QUOTES;
--
select @ID;
--
set @SCHEMA = 'Northwind';
--
SET @STATEMENT = CONCAT('DROP SCHEMA IF EXISTS ','"',@SCHEMA,@ID,'"');
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;
DEALLOCATE PREPARE STATEMENT;
--
SET @STATEMENT = CONCAT('CREATE SCHEMA ','"',@SCHEMA,@ID,'"');
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;
DEALLOCATE PREPARE STATEMENT;
--
set @SCHEMA = 'Sales';
--
SET @STATEMENT = CONCAT('DROP SCHEMA IF EXISTS ','"',@SCHEMA,@ID,'"');
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;
DEALLOCATE PREPARE STATEMENT;
--
SET @STATEMENT = CONCAT('CREATE SCHEMA ','"',@SCHEMA,@ID,'"');
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;

DEALLOCATE PREPARE STATEMENT;
--
set @SCHEMA = 'Person';
--
SET @STATEMENT = CONCAT('DROP SCHEMA IF EXISTS ','"',@SCHEMA,@ID,'"');
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;
DEALLOCATE PREPARE STATEMENT;
--
SET @STATEMENT = CONCAT('CREATE SCHEMA ','"',@SCHEMA,@ID,'"');
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;
DEALLOCATE PREPARE STATEMENT;
--
set @SCHEMA = 'Production';
--
SET @STATEMENT = CONCAT('DROP SCHEMA IF EXISTS ','"',@SCHEMA,@ID,'"');
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;
DEALLOCATE PREPARE STATEMENT;
--
SET @STATEMENT = CONCAT('CREATE SCHEMA ','"',@SCHEMA,@ID,'"');
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;
DEALLOCATE PREPARE STATEMENT;
--
set @SCHEMA = 'Purchasing';
--
SET @STATEMENT = CONCAT('DROP SCHEMA IF EXISTS ','"',@SCHEMA,@ID,'"');
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;
DEALLOCATE PREPARE STATEMENT;
--
SET @STATEMENT = CONCAT('CREATE SCHEMA ','"',@SCHEMA,@ID,'"');
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;
DEALLOCATE PREPARE STATEMENT;
--
set @SCHEMA = 'HumanResources';
--
SET @STATEMENT = CONCAT('DROP SCHEMA IF EXISTS ','"',@SCHEMA,@ID,'"');
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;
DEALLOCATE PREPARE STATEMENT;
--
SET @STATEMENT = CONCAT('CREATE SCHEMA ','"',@SCHEMA,@ID,'"');
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;
DEALLOCATE PREPARE STATEMENT;
--
set @SCHEMA = 'DW';
--
SET @STATEMENT = CONCAT('DROP SCHEMA IF EXISTS ','"',@SCHEMA,@ID,'"');
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;
DEALLOCATE PREPARE STATEMENT;
--
SET @STATEMENT = CONCAT('CREATE SCHEMA ','"',@SCHEMA,@ID,'"');
--
PREPARE STATEMENT FROM @STATEMENT;
EXECUTE STATEMENT;
DEALLOCATE PREPARE STATEMENT;
--
