set echo on 
spool logs/sql/EXPORT_SCHEMA_ALL.log
--
column TABLE_NAME format A32
column SQL_STATEMENT format A128
column STATUS format A16
column RESULT format A64
--
begin
  JSON_EXPORT.DATA_ONLY_MODE(FALSE);
  JSON_IMPORT.DATA_ONLY_MODE(FALSE);
end;
/
var SHOW_SQL_SCRIPT VARCHAR2(120)
--
declare
  SHOW_SQL_SCRIPT VARCHAR2(120);
begin
$IF JSON_FEATURE_DETECTION.CLOB_SUPPORTED $THEN
  SHOW_SQL_SCRIPT := 'SCHEMA_SQL.sql';
$ELSE
  SHOW_SQL_SCRIPT := 'TABLE_BY_TABLE_SQL.sql';
$END
  :SHOW_SQL_SCRIPT := SHOW_SQL_SCRIPT;
end;
/
undef SHOW_SQL_SCRIPT
--
column SHOW_SQL_SCRIPT new_value SHOW_SQL_SCRIPT
--
select :SHOW_SQL_SCRIPT SHOW_SQL_SCRIPT 
  from dual
/
select '&SHOW_SQL_SCRIPT'
  from DUAL
/
set serveroutput on
--
def TARGET_SCHEMA_MODIFIER = 1
--
def SOURCE_SCHEMA = HR
--
def TARGET_SCHEMA = &SOURCE_SCHEMA.&TARGET_SCHEMA_MODIFIER
--
@@CLONE_SCHEMA_SQL &SOURCE_SCHEMA &TARGET_SCHEMA
--
spool logs/sql/EXPORT_SCHEMA_ALL.log APPEND
--
def SOURCE_SCHEMA = SH
--
def TARGET_SCHEMA = &SOURCE_SCHEMA.&TARGET_SCHEMA_MODIFIER
--
@@CLONE_SCHEMA_SQL &SOURCE_SCHEMA &TARGET_SCHEMA
--
spool logs/sql/EXPORT_SCHEMA_ALL.log APPEND
--
def SOURCE_SCHEMA = OE
--
def TARGET_SCHEMA = &SOURCE_SCHEMA.&TARGET_SCHEMA_MODIFIER
--
@@CLONE_SCHEMA_SQL &SOURCE_SCHEMA &TARGET_SCHEMA
--
spool logs/sql/EXPORT_SCHEMA_ALL.log APPEND
--
def SOURCE_SCHEMA = PM
--
def TARGET_SCHEMA = &SOURCE_SCHEMA.&TARGET_SCHEMA_MODIFIER
--
@@CLONE_SCHEMA_SQL &SOURCE_SCHEMA &TARGET_SCHEMA
--
spool logs/sql/EXPORT_SCHEMA_ALL.log APPEND
--
def SOURCE_SCHEMA = IX
--
def TARGET_SCHEMA = &SOURCE_SCHEMA.&TARGET_SCHEMA_MODIFIER
--
@@CLONE_SCHEMA_SQL &SOURCE_SCHEMA &TARGET_SCHEMA
--
spool logs/sql/EXPORT_SCHEMA_ALL.log APPEND
--
def SOURCE_SCHEMA = BI
--
def TARGET_SCHEMA = &SOURCE_SCHEMA.&TARGET_SCHEMA_MODIFIER
--
@@CLONE_SCHEMA_SQL &SOURCE_SCHEMA &TARGET_SCHEMA
--
quit

