# escape=`
FROM yadamu/svr:vs13
#
# Unpack Oracle RDBMS
#
WORKDIR c:/
ENV ORACLE_HOME c:\oracle\rdbms\18.0\db_home1
COPY WINDOWS.X64_180000_db_home.zip C:/
RUN New-Item -ItemType "directory" -Path $env:ORACLE_HOME; `
    Expand-Archive -Path C:\WINDOWS.X64_180000_db_home.zip -DestinationPath $env:ORACLE_HOME; `
    Remove-Item WINDOWS.X64_180000_db_home.zip
#
# Install Oracle Software
#
WORKDIR $ORACLE_HOME
COPY setup.rsp $ORACLE_HOME/inventory/Scripts/
RUN .\setup.exe -silent -responseFile %ORACLE_HOME%/inventory/Scripts/setup.rsp
COPY dbca.rsp .
#
# Execution of NETCA and DBCA deferred to Start.ps1. This allows volumes and hostnames to be assigned using "Docker RUN" or "Docker-Compose"
#
WORKDIR c:/
COPY Start.ps1 .
ENTRYPOINT ["powershell","c:\\Start.ps1"]
#ENTRYPOINT ["powershell","wait-event"]
